/**
 * F1 (2026-10-05): the one e-mail a recipient gets per drain run — counts, the
 * kind of each request, and links. Pure.
 *
 * WHAT IT NEVER CONTAINS. No customer, salesman, route or region name, no NMWC
 * code, no phone, no reason: its input has no field that could carry one. It is
 * built from the notification's kind and the request's id and type only — never
 * from Notification.title or .body (which carry the legal name) and never from
 * CustomerEdit.decisionReason (the salesman's or a reviewer's free text). An
 * e-mail leaves the app for Google and for each recipient's mailbox, beyond any
 * retention or erasure the app controls (docs/compliance/DATA-RESIDENCY-REGISTER.md),
 * so it says only "there is something for you, here". The request's own page
 * says what it is, to someone signed in and in scope.
 *
 * Plain text only: no HTML to escape and no HTML-to-text regex
 * (tests/unit/strip-html.test.ts keeps that regex in one file). Short English with
 * an Arabic line. A line saying the CRM never asks for a password by e-mail: a
 * message from a known mailbox with links teaches people to follow links, so it
 * says what a genuine one never does. No action or decision token travels in a
 * link: approval stays on the page (N01).
 */
import type { Role } from '@prisma/client';
import { hrefFor } from '../notification-links';
import { headerSafe } from './header';

/** The request a line is about, as the app's own records type it. */
export type RequestType = 'CREATE' | 'UPDATE' | 'CLOSE' | 'REACTIVATION';

export type DigestItem = {
  kind: 'EDIT_SUBMITTED' | 'EDIT_STAGE_ADVANCED' | 'REACTIVATION_REQUESTED' | 'REQUEST_FYI' | 'SLA_BREACH';
  editId: string;
  requestType: RequestType;
};

export const DIGEST_HEADERS: Readonly<Record<string, string>> = {
  // RFC 3834: generated by a machine, so auto-responders must not answer it.
  'Auto-Submitted': 'auto-generated',
  // Exchange / Outlook: no out-of-office or read receipts back.
  'X-Auto-Response-Suppress': 'All',
};

const REQUEST_WORDS: Record<RequestType, string> = {
  CREATE: 'a new-customer request',
  UPDATE: 'a customer update request',
  CLOSE: 'a close-shop request',
  REACTIVATION: 'a shop reactivation request',
};

function line(item: DigestItem): string {
  const what = REQUEST_WORDS[item.requestType];
  switch (item.kind) {
    case 'EDIT_SUBMITTED':
      return `Waiting for your review: ${what}`;
    case 'EDIT_STAGE_ADVANCED':
      return `Now at your approval step: ${what}`;
    case 'REACTIVATION_REQUESTED':
      return `Waiting for your decision: ${what}`;
    case 'SLA_BREACH':
      return `Overdue: ${what}`;
    case 'REQUEST_FYI':
      return `For your information: ${what} was submitted`;
  }
}

export const MUST_ACT_ITEM_KINDS: ReadonlySet<DigestItem['kind']> = new Set([
  'EDIT_SUBMITTED',
  'EDIT_STAGE_ADVANCED',
  'REACTIVATION_REQUESTED',
  'SLA_BREACH',
]);

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export function renderDigest(input: {
  items: DigestItem[];
  /** The recipient's role: where a link goes depends on it, as in the inbox. */
  role: Role;
  linkOrigin: string;
  subjectPrefix: string;
  maxItems: number;
}): { subject: string; text: string; headers: Record<string, string> } {
  const { items, linkOrigin } = input;
  const act = items.filter((i) => MUST_ACT_ITEM_KINDS.has(i.kind)).length;
  const fyi = items.length - act;
  const parts: string[] = [];
  if (act > 0) parts.push(`${plural(act, 'request', 'requests')} waiting for you`);
  if (fyi > 0) parts.push(`${plural(fyi, 'request', 'requests')} for your information`);
  const subject = headerSafe(`${input.subjectPrefix}NMWC CRM: ${parts.join(', ')}`);

  // Must-act lines first, then the information lines, each in the order given.
  const ordered = [...items].sort(
    (a, b) => Number(!MUST_ACT_ITEM_KINDS.has(a.kind)) - Number(!MUST_ACT_ITEM_KINDS.has(b.kind))
  );
  const shown = ordered.slice(0, Math.max(1, input.maxItems));
  const lines: string[] = [
    'Hello,',
    '',
    `You have ${plural(items.length, 'new item', 'new items')} in the NMWC customer CRM.`,
    '',
  ];
  for (const item of shown) {
    const path = hrefFor({ kind: item.kind, editId: item.editId, customerId: null, edit: { isReactivation: item.requestType === 'REACTIVATION' } }, input.role);
    lines.push(line(item), `${linkOrigin}${path}`, '');
  }
  const more = items.length - shown.length;
  if (more > 0) lines.push(`…and ${more} more: ${linkOrigin}/notifications`, '');
  lines.push(
    'Open a link to see the request in the CRM. If you are asked to sign in, sign in, then open the link again.',
    '',
    `The CRM never asks for your password by e-mail. Sign in only at ${linkOrigin}.`,
    '',
    '—',
    `لديك ${items.length} من العناصر الجديدة في نظام عملاء NMWC. افتح الروابط أعلاه لعرضها.`,
    'لا يطلب النظام كلمة المرور عبر البريد الإلكتروني أبداً.',
    '',
    'This message was sent automatically. Replies are not read.'
  );
  return { subject, text: lines.join('\n'), headers: { ...DIGEST_HEADERS } };
}
