# Final pre-go-live adversarial bug hunt — 2026-07-21

137 agents (2 rounds x 9 lenses x 3-lens adversarial verify + 2 critics), 0 errors. **37 confirmed** (7 P1, 14 P2, 16 P3). NOTE: agents read the snapshot at launch, BEFORE the F-UAT-7 fix — finding on services/imports.ts:661 (in-file dup) is already fixed (commit 382e9c5).

## [0] P1 <regressions> — SR-USR-01 allowlist closed the last path to create ACCOUNTANT/FINANCE_MANAGER/GM — every net-new customer CREATE stalls forever
**File:** `lib/permissions.ts:223`

**Claim:** After the SR-USR-01 fix there is NO in-application way to provision the approver-tier roles (ACCOUNTANT, FINANCE_MANAGER, GM), yet the create-approval chains REQUIRE them. Result: in a clean pilot deployment, no net-new customer (cash OR credit) can ever be finalized — the request is permanently stranded at the Accountant step with no eligible approver. Enrichment (single-Supervisor UPDATE chain) is unaffected, so the pilot's core flow still works; the DB-seed workaround exists but is outside the app.

**Evidence:** lib/permissions.ts:223-227 sets MANAGER_ADMINISTRABLE_ROLES = [SALESMAN, SUPERVISOR, VIEWER]; services/users.ts:83-88 (createUserCore) and :347-351 (updateUserRoleCore) reject any role outside that allowlist, so the Manager /users UI can no longer mint approvers (before SR-USR-01 the blocklist only shielded MANAGER/STEWARD, so a Manager COULD create them). services/users.ts:20-27 requireManager() throws for any role !== MANAGER, so a STEWARD cannot use these UI actions at all — the comment's claim that approvers are 'Steward-provisioned' has no code path. services/imports.ts:70 VALID_ROLES = [SALESMAN, SUPERVISOR, MANAGER, STEWARD, VIEWER] excludes ACCOUNTANT/FINANCE_MANAGER/GM, and :222-228 rejects them, so the account-master import can't create them either. lib/approval-chains.ts:68-77 makes ACCOUNTANT the mandatory FINAL step of the CASH create chain and FINANCE_MANAGER+GM+ACCOUNTANT the CREDIT chain; lib/create-finalize.ts only runs after that final approval. prisma/seed-muscat-pilot.ts creates only MANAGER/STEWARD/SUPERVISOR/SALESMAN — no approvers — so the shipped pilot seed does not fill the gap. (The only place approvers are created is prisma/synthetic.ts:222-240, a prod-guarded test seed.) app/(app)/users/CreateUserForm.tsx:7-16 still lists all 8 roles in the dropdown, so a Manager can pick 'Accountant' and only discovers on submit that it is rejected.

**Scenario:** Fresh pilot: run seed-muscat-pilot.ts, deploy. A salesman submits a net-new customer via /customers/new (CASH). Supervisor approves → edit advances to currentStepIndex 1 (ACCOUNTANT step). No ACCOUNTANT user exists; canActOnStep can never be satisfied. The SLA sweep escalates to FINANCE_MANAGER/GM (also nonexistent) → escalation audience resolves empty. The CustomerEdit sits SUBMITTED at the Accountant step indefinitely; the customer is never materialized. There is no in-app action any role can take to unblock it.

## [1] P1 <approval-engine> — EL-04 approve-time mandatory-field re-check blocks ALL branch-CLOSE approvals for imported/incomplete customers
**File:** `nmwc-crm-consolidation-e10c1e/services/edits.ts:1061`

**Claim:** The close-shop request is a salesman-submitted CustomerEdit created directly (services/reactivations.ts:208-231) as state=SUBMITTED, target=BRANCH, pendingRole=SUPERVISOR, process=UPDATE (default), whose ONLY fieldChange is `branch.<id>.status = CLOSED`. It bypasses submitEditCore's submit-time mandatory gate (it is created via prisma.customerEdit.create, not submitEditCore) but rides the generic approveEditCore for supervisor approval. At the FINAL UPDATE branch, EL-04 (services/edits.ts:1061-1082) re-runs collectMissingMandatory because the submitter is a SALESMAN. collectMissingMandatory (services/edits.ts:107-196) requires customer.crPhotoId (line 168) and, for EVERY live branch, address>=3 / gps / dayOfVisit / shopPhotoId (line 187) / signboardPhotoId (line 191), plus channelId/subChannelId/primaryPhone/contactPerson. Imported/legacy master customers (the bulk of a customer-master-consolidation CRM) have no field-captured photos and often no channel/GPS, so `missing` is non-empty and approve throws ConflictError('NEEDS_REUPLOAD'). The closure therefore can NEVER be approved through the salesman->supervisor flow; the request stays stuck SUBMITTED (rejecting it does not close the shop, and markBranchClosedCore always mints a fresh edit, so re-submitting loops the same wall). collectMissingMandatory scans ALL branches of the customer, so even closing a complete branch is blocked if any sibling branch is incomplete.

**Evidence:** services/edits.ts:1061 `if (submitterUser?.role === Role.SALESMAN)` gates the re-check purely on submitter role, with NO exemption for a branch-status-only CLOSE edit. services/reactivations.ts:149 `require([Role.SALESMAN])`; :218 `pendingRole: Role.SUPERVISOR`; :224-226 fieldChanges = [{field:`branch.${branch.id}.status`, before, after:'CLOSED'}]. collectMissingMandatory hard-requires customer.crPhotoId (services/edits.ts:168) and per-branch signboardPhotoId (services/edits.ts:191) which imported masters lack. rejectEditCore does NOT run collectMissingMandatory, and for a single-step chain resolveRejectTarget(0,...) returns TO_SALESMAN (NEEDS_CORRECTION) — so the only terminal states reachable are 'stuck SUBMITTED' or 'rejected, still open/ACTIVE'.

**Scenario:** Salesman visits an imported shop (customer created via master import/promote, so crPhotoId=null, branch.signboardPhotoId=null), finds it shut, captures a fresh photo, and submits markBranchClosedAction. The Supervisor opens /approvals and clicks Approve. approveEditCore reaches EL-04 (edits.ts:1061), collectMissingMandatory returns {customer.crPhoto, branch.<id>.signboardPhoto, ...}, and the approval throws NEEDS_REUPLOAD. The shop can never be marked CLOSED via the normal flow; the only escape is a Manager/Steward force-closing via the direct-write edit form (submitEditCore isDirectWrite, edits.ts:475), which is unavailable to the field force and bypasses the photo-evidence gate.

## [2] P1 <import-promote> — In-file phone/CR duplicate check is not scoped by cust_code — quarantines a multi-branch customer's own rows against itself
**File:** `C:\Users\abdulr\Desktop\NMWC-CRM\.claude\worktrees\nmwc-crm-consolidation-e10c1e\services\imports.ts:661`

**Claim:** The in-file phone and CR duplicate detectors (phonesInFile/crsInFile) key only on the normalized value and never on cust_code, so when a customer spans multiple branch rows and repeats its own phone or CR number across those rows, EVERY one of that customer's rows is flagged 'duplicate ... in this file' and QUARANTINED. Quarantined rows are excluded from promote (cleanRows = state CLEAN only, line 787-789), so the entire customer silently fails to import. This is the exact opposite of the documented contract on line 522 ('phone collision across DIFFERENT cust_codes is flagged') and is inconsistent with the master cross-check on the same rows, which DOES exclude self via `.some((code) => code !== custCode)` (lines 658-660, 664-666). CR number is a legal-entity attribute shared by all branches of one customer (schema line 311 'legal entity attribute'; lib/cr.ts), so a master that lists cr_no on each branch row will quarantine every multi-branch customer. The imminent 3,300-row real master is precisely 'one row per branch, cust_code/cust_name repeated' (import/page.tsx expected-columns; promote design comment lines 514-516).

**Evidence:** Build loop lines 581-599 pushes row numbers into phonesInFile/crsInFile keyed ONLY by normalized value (no cust_code). Checks: line 655-657 `if (phone && phonesInFile.get(phone)!.length > 1)` quarantines; line 661-663 `if (crNorm && crsInFile.get(crNorm)!.length > 1)` quarantines. Contrast the master checks lines 658-660 and 664-666 which correctly ignore same custCode. The promote-reconciliation and import-reconciliation fixtures only ever place duplicate CR/phone on DIFFERENT cust_codes (manifest ZZDUP-A/ZZDUP-B, ZZPH-A/ZZPH-B), so the same-customer case is untested. There is no per-row un-quarantine UI (import/[batchId]/page.tsx only renders a whole-batch Promote button), so the steward's only recourse is editing the source sheet — and the 'duplicate CR in this file' message invites them to delete the shared CR or the 'duplicate' rows, risking real data loss.

**Scenario:** Real master has customer ACME with 3 branches on 3 rows, each row carrying cr_no='1234567' (the shared legal CR). Upload flags all 3 rows cr_no 'duplicate CR in this file (also rows ...)' → all 3 QUARANTINED → 0 CLEAN rows for ACME → ACME is absent from the promoted master. Repeat across every multi-branch customer with a repeated CR/phone.

## [3] P1 <temix> — paymentTerms CASH↔CREDIT flip via ordinary UPDATE edit bypasses the owner-locked credit-onboarding chain and corrupts the Temix credit push
**File:** `services/edits.ts:450`

**Claim:** An UPDATE edit is allowed to change Customer.paymentTerms with no transition guard, and the UPDATE approval chain is unconditionally a single Supervisor step — so a CASH↔CREDIT flip is approved by one Supervisor, entirely bypassing the owner-locked CREDIT chain (Salesman → Supervisor → Finance Manager → GM → Accountant, plus credit-limit capture and guarantee documents). The flipped customer then re-queues PENDING_UPLOAD and pushes a corrupted credit record to Temix.

**Evidence:** paymentTerms is an accepted edit field (lib/validation/edit.ts:19 `paymentTerms: z.nativeEnum(PaymentTerms).optional()`) and is in CUSTOMER_FIELDS (services/edits.ts:67), so it is diffed (edits.ts:370) and written by applyEditChanges (edits.ts:602-604). There is NO transition guard on paymentTerms in edits.ts (grep of the file shows only CUSTOMER_FIELDS membership, the salesman crNumber-skip at :146, and the chain snapshot at :450/:455) — in sharp contrast to the elaborate CLOSED/SUSPENDED status guards at edits.ts:315-335 and :393-411. The chain is resolved from the CURRENT terms via resolveChain(EditProcess.UPDATE, customer.paymentTerms) at edits.ts:450, and resolveChain returns `[SUPERVISOR_STEP]` for EVERY UPDATE regardless of terms (lib/approval-chains.ts:64-65). creditLimit/paymentTermDays are NOT in CUSTOMER_FIELDS (edits.ts:65-77), so the flip cannot capture them and the DB CHECK constraints only enforce non-negativity/range, not CASH⇒null (prisma/migrations/20260715120100_phase1_tables/migration.sql:257-262). On the next Temix batch the re-queued customer (edits.ts:684-688 sets PENDING_UPLOAD) is emitted by buildTemixRows with `credit_limit` blank because `isCredit && c.creditLimit != null` is false (lib/temix.ts:93) and guarantee_docs=0. isFieldLocked keys the crNumber lock purely on paymentTerms==='CREDIT' (lib/permissions.ts:83), so a CREDIT→CASH flip also unlocks crNumber edits for salesmen — the exact risk flagged in docs/discovery/raw-evidence/x-contradictions.md:156.

**Scenario:** A Salesman submits an enrichment UPDATE on a CASH customer with customer.paymentTerms='CREDIT' (accepted by customerEditSchema; not UI-exposed in EnrichmentForm.tsx, so it requires invoking the server action directly). collectMissingMandatory does not require creditLimit and skips crNumber for salesmen, so nothing blocks submit. The chain is [Supervisor]; the submitter's Supervisor approves. applyEditChanges writes paymentTerms=CREDIT while creditLimit/paymentTermDays stay null, and edits.ts:684-688 re-queues the customer to PENDING_UPLOAD. The next Steward batch (lib/temix.ts buildTemixRows) hands Temix a CREDIT customer with a BLANK credit_limit and guarantee_docs=0 — a credit customer onboarded into the ERP with zero Finance Manager/GM approval, no approved limit, and no guarantee evidence. The reverse (CREDIT→CASH by one Supervisor) removes a customer's credit status without finance sign-off, leaves a stale non-null creditLimit in the DB (no CHECK prevents it), and unlocks the CR number for salesman edits.

## [4] P1 <import-promote> — Customer master re-import silently full-overwrites existing customers' CRM-owned fields (flips CREDIT->CASH, nulls phone/CR/contact) — the CONFIRMED 'absent column' fix was applied to the refresh lane only
**File:** `services/imports.ts:1080`

**Claim:** In promoteCustomerBatchCore the non-refresh branch runs tx.customer.upsert with an update: block (imports.ts:1080-1089) that unconditionally overwrites paymentTerms (defaulting to CASH), primaryPhone/primaryPhoneNorm, contactPerson, crNumber/crNumberNorm and legalName with the sheet row's values, while NOT touching creditLimit, paymentTermDays or temixSyncState. This branch is reached for any EXISTING live customer whose row lacks a temix_code, because isRefresh = !!existing && !existing.deletedAt && !!first.temixCode (imports.ts:1018). So a plain master re-import of an already-known customer silently (a) flips a CREDIT customer to CASH while leaving its creditLimit/paymentTermDays non-null (CASH+creditLimit inconsistency), and (b) nulls out primaryPhone/contactPerson/crNumber whenever the re-import sheet omits those columns. This is exactly the 'absent payment_terms column silently flips CREDIT->CASH' class that was previously CONFIRMED and fixed — but the presence-aware guard (paymentTermsPresent) was only wired into the Temix REFRESH lane (imports.ts:1033-1051); the full-upsert lane still hard-defaults CASH. The comment at imports.ts:673-674 ('Legacy create/full-upsert paths keep the CASH default unchanged') shows this was a deliberate scoping decision whose premise — that the full-upsert path never hits an existing CREDIT customer — is false.

**Evidence:** imports.ts:1018 `const isRefresh = !!existing && !existing.deletedAt && !!first.temixCode;` — a row without temix_code on an existing customer takes the else branch. imports.ts:1080-1089 update block sets `paymentTerms: pt` (pt = CASH unless the sheet says CREDIT, imports.ts:968) and `primaryPhone: first.phone` / `contactPerson: first.contactPerson` / `crNumber: first.crNumber` (each null when the column is absent — parsed via `stripHtml(...) || null`, imports.ts:723-730), and deliberately omits creditLimit/paymentTermDays. create-finalize.ts:180-197 creates approved CREDIT customers with `paymentTerms: draft.paymentTerms`, `temixCode: null`, `temixSyncState: PENDING_UPLOAD`, `creditLimit: isCredit ? ...` — the exact rows this lane clobbers. The parse-time master collision checks only quarantine a phone/CR under a DIFFERENT code (imports.ts:658 `.some((code) => code !== custCode)`, imports.ts:664), so a same-custCode re-import stays CLEAN and flows straight into this update path.

**Scenario:** A salesman-submitted CREDIT customer is approved: create-finalize.ts writes paymentTerms=CREDIT, creditLimit=5000, temixCode=null, temixSyncState=PENDING_UPLOAD. Before the Temix outbound batch runs, the Steward re-imports a corrected customer master (or the same 3,300 master re-run) whose row for that nmwcCode has cust_code + cust_name but no payment_terms and no temix_code column. isRefresh=false, so tx.customer.upsert.update executes: paymentTerms becomes CASH, primaryPhone/contactPerson/crNumber become null, but creditLimit stays 5000 and temixSyncState stays PENDING_UPLOAD. The customer is now a CASH record carrying a stale 5000 credit limit with wiped contact/CR data, the import row is marked PROMOTED with no warning, and it is still queued for Temix upload (services/temix.ts CUSTOMER_SELECT emits creditLimit/paymentTermDays), pushing an inconsistent credit figure to the ERP. Workaround exists (always include payment_terms + full contact columns + temix_code on every re-imported row, or never re-import an existing customer), so it is P1 not P0.

## [5] P1 <temix> — Temix master-refresh silently degrades to a destructive full-upsert on a temix_code header mismatch, NULLing CRM-owned phone/CR/contact fields
**File:** `services/imports.ts:1018`

**Claim:** The refresh-vs-upsert routing hinges entirely on each row's temix_code being parsed via four hard-coded header fallbacks (imports.ts:696-698 = temix_code | temixcode | 'TEMIX CODE' | 'Temix Code'). The exact Temix header row is an OPEN owner question (lib/temix.ts:74-76 Q-temix-headers) and the first real Temix refresh is untested (RK-10). If Temix's extract names its ERP-code column anything else (or the column is absent), EVERY row parses temixCode=null, so isRefresh (imports.ts:1018 = !!existing && !existing.deletedAt && !!first.temixCode) is false and the narrow, field-ownership-safe refresh update (imports.ts:1033-1051) is skipped in favor of the plain upsert UPDATE (imports.ts:1078-1089).

**Evidence:** The plain UPDATE block sets primaryPhone/primaryPhoneNorm=first.phone, contactPerson=first.contactPerson, crNumber/crNumberNorm=first.crNumber (imports.ts:1083-1087). first.phone is normalizePhone(...) which is null when the Temix extract lacks a phone column, and first.crNumber/contactPerson are null when those columns are absent (a Temix extract does not hold CRM-side contact enrichment). Prisma treats explicit null as SET-to-null, so these CRM-owned fields are WIPED, and legalName is overwritten with Temix's value — the exact clobber the dedicated refresh lane exists to prevent (sla-notif-sync 3.5 field-ownership). Because it is not a refresh, no temix_code is backfilled and UPLOADED->SYNCED never fires, so the customers also stay stuck UPLOADED. Compounding this, ALL crosswalk safety guards — including the 'customer is archived — resolve its Temix deactivation first' guard — are nested under `if (first.temixCode)` (imports.ts:986-1016), so a null temixCode bypasses every guard and the plain upsert can even mutate/resurrect fields on a soft-deleted customer's row (upsert keys on nmwcCode regardless of deletedAt). The rows are CLEAN (blank phone/cr trigger no validation), so nothing quarantines. Only a per-batch summary is audited (imports.ts:1258) — no per-field before-state — so the wiped phone/CR/contact values are recoverable only from a DB backup. This violates the codebase-wide 'fail-closed / quarantine rather than silently overwrite' philosophy at the single highest-stakes, least-tested moment (the first production Temix refresh).

**Scenario:** Steward runs the first real Temix master-refresh via /import. Temix's export names its code column e.g. 'ERP_CODE' or 'TemixCode' (not one of the 4 fallbacks) and omits CRM contact columns. All existing customers parse temixCode=null -> plain upsert UPDATE -> primaryPhone, crNumber, contactPerson set to NULL and legalName overwritten; no code backfill, no state settle. Mass silent loss of CRM-owned contact data with no error and no quarantine.

## [6] P1 <edge-null> — Customer-master re-import silently downgrades existing CREDIT customers to CASH (F-12 presence-aware fix applied to only one of two lanes)
**File:** `services/imports.ts:1082`

**Claim:** In promoteCustomerBatchCore, the non-refresh full-upsert UPDATE branch writes `paymentTerms: pt` unconditionally (line 1082), where `pt = first.paymentTerms === 'CREDIT' ? 'CREDIT' : 'CASH'` (line 968) and `first.paymentTerms` defaults to 'CASH' whenever the sheet's payment_terms cell is absent/blank (parse: lines 675-682). Re-importing an existing CREDIT customer via a plain master row that omits BOTH temix_code and payment_terms therefore silently flips the live customer to CASH. The `paymentTermsPresent` guard that the adversarial-review F-12 fix added to prevent exactly this CREDIT→CASH flip is consulted ONLY in the refresh branch (lines 1033-1051), never in this full-upsert update branch — the fix is asymmetric/incomplete.

**Evidence:** Line 968: `const pt = first.paymentTerms === 'CREDIT' ? 'CREDIT' : 'CASH';`. Lines 1078-1089 (non-refresh upsert): `update: { legalName: first.custName, paymentTerms: pt, primaryPhone: first.phone, ... }` — sets paymentTerms=pt but does NOT touch creditLimit/paymentTermDays (only the `create` branch, lines 1090-1108, sets them). Parse (lines 675-682): `let paymentTerms='CASH'; const paymentTermsPresent = ptRaw==='CASH'||ptRaw==='CREDIT'; ... else if (ptRaw==='CREDIT') paymentTerms='CREDIT'` — an absent column yields CASH + paymentTermsPresent=false but the row is still CLEAN (both columns optional per the comment at lines 690-695). isRefresh (line 1018) is false when first.temixCode is null, so the update branch runs. The refresh branch (lines 1033-1051) correctly uses `ptPresent` to keep current terms, proving the intended semantics that the full-upsert branch omits. Downstream, lib/temix.ts buildTemixRows (lines 93-96) gates credit_limit/payment_term_days on `isCredit`, so the flipped customer's credit terms are dropped from the Temix outbound — Temix-side credit-term loss.

**Scenario:** Existing customer C-1001 is CREDIT with creditLimit=5000, paymentTermDays=30. Steward uploads a customer-master .xlsx (e.g. to bulk-fix addresses) whose row for C-1001 carries cust_code + cust_name but no `payment_terms` column and no `temix_code` column — a supported 'plain master sheet' per the module docs. Row parses CLEAN. Promote takes the non-refresh update path and writes paymentTerms=CASH, leaving creditLimit=5000/paymentTermDays=30 orphaned. The customer is now an inconsistent CASH record with a non-null credit limit; field-lock/approval-chain routing treats it as CASH; and the next Temix batch emits blank credit_limit/payment_term_days for it, losing the credit terms in the ERP. No warning is surfaced (only F-17 UNASSIGNED warnings are). Fix: make the full-upsert update branch presence-aware like the refresh branch — only write paymentTerms (and null credit figures) when first.paymentTermsPresent === true; otherwise leave paymentTerms/creditLimit/paymentTermDays untouched on an existing customer.

## [7] P2 <approval-engine> — CREATE approval scope drifts: queue/detail authorize on frozen EditBranchDraft.regionId while approve/reject/finalize authorize on the route's CURRENT region (RK-2 wedge still live)
**File:** `(app)/approvals/page.tsx:74`

**Claim:** For a net-new CREATE request, the approvals queue and detail page compute the region scope from the FROZEN EditBranchDraft.regionId column, but approveEditCore/rejectEditCore and finalizeCreateInTx all compute it from the route's CURRENT region (route.regionId via a join). EditBranchDraft.regionId (schema line 646) is a plain frozen copy set to route.regionId at submit (services/creates.ts:291) and is only refreshed on a full resubmit (creates.ts:391 deleteMany + :410 recreate) — never while a request sits SUBMITTED mid-chain. If a Steward re-regions a route (A->B) during the multi-day SUP->FM->GM->ACC credit chain (a scenario the finalize code itself anticipates in lib/create-finalize.ts:98-101), the CREATE request becomes un-actionable by any Accountant: the OLD-region accountant sees it in queue/detail (draft.regionId=A) but approve denies (route.regionId=B not in their managedRegions), while the NEW-region accountant can approve but the row is invisible to them (draft.regionId=A) and a deep link 404s.

**Evidence:** Queue (app/(app)/approvals/page.tsx:73-77): `branchDrafts: { some: { regionId: { in: scope.managedRegionIds } } }` uses the frozen draft column. Detail (app/(app)/approvals/[id]/page.tsx:84-88): `regionIds = isCreate ? edit.branchDrafts.map(b => b.regionId) ...` then notFound() if no overlap — also frozen. Approve (services/edits.ts:758-761): `scopeBranches = edit.branchDrafts.map(d => ({ regionId: d.route.regionId, ... }))` — CURRENT route region via the include at edits.ts:721. Reject mirrors it (services/edits.ts:1309-1312). Finalize re-derives from route.regionId (lib/create-finalize.ts:102-116, :122-127). Schema confirms no route-sync trigger on EditBranchDraft.regionId (prisma/schema.prisma:646). Approve is gated on the CURRENT region, so there is no wrong-region approval / escalation — the only harm is a visibility-vs-authorization wedge.

**Scenario:** A CREDIT create for a Sohar-route shop is submitted (branchDraft.regionId = North Batinah). It clears SUP, FM, GM over two days. A Steward runs a route-master import that moves that route into a new region. At the Accountant step: the North-Batinah accountant sees the request in their queue but Approve returns ForbiddenError (route now in the new region); the new-region accountant never sees it and a deep link returns notFound(). The request wedges SUBMITTED until an admin re-regions the route back or force-completes it.

## [8] P2 <import-promote> — Branch 'Address pending' fallback is unreachable when address+branch_name+sales_region are all blank → whole customer group REJECTED at promote by the B-20 CHECK
**File:** `C:\Users\abdulr\Desktop\NMWC-CRM\.claude\worktrees\nmwc-crm-consolidation-e10c1e\services\imports.ts:924`

**Claim:** The resolved branch address is `p.address ?? [p.branchName, p.regionCode].filter(Boolean).join(', ') ?? 'Address pending'`. When address, branch_name and sales_region are all blank, the middle operand evaluates to '' (empty string) — because `[null,null].filter(Boolean).join(', ')` is '' which is NOT nullish — so the `?? 'Address pending'` guard never fires and address is stored as ''. The DB CHECK constraint Branch_address_minlength requires `length(btrim(address)) >= 3` (migration 20260510120000, lines 217-222), so the branch INSERT raises, the per-group $transaction rolls back, and the customer (parent + row) is marked REJECTED instead of importing with the intended placeholder. The 'Address pending' safety net that was written specifically to keep sparse rows importable is dead code for exactly the sparse rows it was meant to save.

**Evidence:** imports.ts lines 924-928: `address: p.address ?? [p.branchName, p.regionCode].filter(Boolean).join(', ') ?? 'Address pending'`. `??` is left-associative and '' is not nullish, so for all-blank inputs the result is '' not 'Address pending'. Parse stores each field as `stripHtml(...) || null` (lines 723-727), so blanks become null and filter(Boolean) drops them → join → ''. B-20 CHECK migration 20260510120000_senior_audit_remediation/migration.sql line 220: `CHECK (length(btrim("address")) >= 3)`. The row was CLEAN at upload (address is not required at parse), so it reaches promote and fails there, surfacing only as a cryptic 'promote failed (Pxxxx)' REJECTED row. Both reconciliation tests give every promote row an explicit address, so this path is untested.

**Scenario:** A legacy master row has cust_code + cust_name only (no address, no branch_name, no sales_region). It passes upload CLEAN, then at promote address resolves to '' → Branch_address_minlength violation → group transaction rolls back → customer not created, row REJECTED with an opaque code, instead of importing with address='Address pending'.

## [9] P2 <import-promote> — paymentTermsPresent guard was applied only to the Temix-refresh lane; the non-refresh upsert UPDATE still force-writes CASH when payment_terms is absent, silently flipping an existing CREDIT customer to CASH
**File:** `C:\Users\abdulr\Desktop\NMWC-CRM\.claude\worktrees\nmwc-crm-consolidation-e10c1e\services\imports.ts:1080`

**Claim:** The presence-aware fix that stops an absent payment_terms column from flipping CREDIT customers to CASH (the adversarial-review CONFIRMED finding) is implemented ONLY inside the refresh branch (isRefresh, lines 1033-1051, gated on temix_code). The non-refresh upsert takes `pt = first.paymentTerms === 'CREDIT' ? 'CREDIT' : 'CASH'` (line 968, where first.paymentTerms defaults to 'CASH' whenever the column is blank) and writes `paymentTerms: pt` unconditionally in BOTH create and update (lines 1080/1092). isRefresh is false whenever the row carries no temix_code, so re-importing an EXISTING live CREDIT customer with a blank/absent payment_terms and no temix_code flips it to CASH — the same defect the fix claims to close, just in the lane the comment (lines 673-674 'Legacy create/full-upsert paths keep the CASH default unchanged') deliberately left unguarded. creditLimit/paymentTermDays are not cleared on this path, leaving an inconsistent CASH-with-credit-figures record that the Temix outbound would then export as CASH. The same non-refresh UPDATE path also overwrites CRM-owned legalName/primaryPhone/contactPerson/crNumber and resets the branch route/region to UNASSIGNED when route is blank — precisely the field-ownership clobber the refresh lane was designed to avoid.

**Evidence:** Line 968 `const pt = first.paymentTerms === 'CREDIT' ? 'CREDIT' : 'CASH';`. Parse default line 676 `let paymentTerms = 'CASH'` when the column is absent, with paymentTermsPresent=false (line 677). isRefresh = `!!existing && !existing.deletedAt && !!first.temixCode` (line 1018) — false without temix_code. Non-refresh update (lines 1078-1089) writes `paymentTerms: pt` with no presence check, unlike the refresh branch which uses `paymentTerms: ptPresent ? pt : undefined` (line 1039). Credit-onboarded CREDIT customers can exist with temixSyncState PENDING and no temixCode yet (schema lines 314-324), so this is reachable outside a Temix context.

**Scenario:** A CREDIT customer (created via credit onboarding, no temix_code yet, creditLimit=5000) is included in a re-uploaded master to fix its branch address. Its row has no temix_code and a blank payment_terms cell. Promote takes the non-refresh update path, writes paymentTerms=CASH (creditLimit untouched) → customer is now CASH+5000 limit, and the next Temix outbound exports it as CASH.

## [10] P2 <data-integrity> — detachPhoto never recomputes completenessScore — rollup drift
**File:** `services/photos.ts:325`

**Claim:** detachPhotoCore's transaction (lines 325-357) nulls the slot pointer (crPhotoId/shopPhotoId/signboardPhotoId), soft-deletes the Attachment, and writes an audit row, but NEVER recomputes the customer's or branch's stored completenessScore. Its sibling attachPhotoCore does recompute on every attach (customer at lines 164-169 via scoreCustomer; branch at lines 246-258 via scoreBranch + scoreCustomer). Removing a photo is thus asymmetric: the score stays inflated by the photo's weight.

**Evidence:** lib/completeness.ts: scoreCustomerOnly grants +10 for crPhotoId (line 46); scoreBranch grants +10 for shopPhotoId (line 55) and +10 for signboardPhotoId (line 56), which then propagate into the customer score via the branch average (scoreCustomer lines 73-81). The stored completenessScore column is read directly — never recomputed on read — by the minScore/maxScore filter (lib/customer-filters.ts line 193: where.completenessScore = { gte/lte }), the customer detail rings (app/(app)/customers/[id]/page.tsx lines 85 & 149), the dashboard average (app/(app)/dashboard/page.tsx line 84 _avg), and both CSV exports (services/customer-export.ts line 216, services/exports.ts line 166). detachPhotoAction is a directly-reachable public server action (salesman removes own photo; steward/manager detach in scope), separate from the edit-approval finalize path.

**Scenario:** A customer has a CR photo (score includes +10) and stored completenessScore = 82 (band 'high'). A salesman/steward calls detachPhotoAction to remove that photo. crPhotoId is nulled and the attachment soft-deleted, but completenessScore stays 82. The customer's TRUE score is now 72, yet: (a) it still passes a work-list filter of minScore>=80 and shows a 'high' ring on the detail page and card, (b) it still shows a stale 82 in the CSV export handed to the owner, and (c) the dashboard average completeness is skewed upward. The stale value only self-heals if some later attach/edit happens to recompute — nothing schedules a recompute, so the drift can persist indefinitely.

## [11] P2 <data-integrity> — photo-gc hard-deletes the DB row even when R2 tagging fails — permanent orphan
**File:** `cron/photo-gc/route.ts:62`

**Claim:** In the GC loop the PutObjectTaggingCommand failure is only counted (r2Errors++) and logged (lines 55-60); the subsequent prisma.attachment.delete (line 62) then runs UNCONDITIONALLY, permanently deleting the only DB record of the object (its r2Key). The two operations are not gated on each other.

**Evidence:** The job's own header states its purpose: 'Without it, R2 storage grows unboundedly with every photo replacement and detach.' The R2 side is not a hard delete — line 42/47-52 tags the object gc-marked=true so a tag-SCOPED R2 lifecycle rule expires it. If tagging fails for a transient reason (throttle/timeout/network), the object is never tagged and therefore never lifecycle-expired, while line 62 still removes the DB row that held the r2Key. The object is now orphaned in R2 forever with no DB pointer. The catch comment (lines 56-58) assumes every failure means 'R2 may already be missing — that's fine', conflating 'object already gone' (safe) with 'transient failure, object still present' (leak).

**Scenario:** sla/photo-gc cron runs; for a 30-day-old soft-deleted attachment the S3 tagging call times out (transient). r2Errors becomes 1, the warn is logged, then prisma.attachment.delete removes the row. The R2 binary remains, untagged, so the lifecycle rule never collects it, and there is no longer any DB row to re-drive GC against it. This reintroduces the exact unbounded-storage leak the cron exists to prevent, for every object whose tag call transiently fails. Fix: only delete the DB row when tagging succeeded (or when the object is confirmed absent), otherwise leave deletedAt set so the next sweep retries.

## [12] P2 <edge-null> — Reactivation reviewer is shown stale branch slot photos, never the fresh evidence the gate collected
**File:** `C:\Users\abdulr\Desktop\NMWC-CRM\.claude\worktrees\nmwc-crm-consolidation-e10c1e\app\(app)\reactivations\page.tsx:83`

**Claim:** The Manager reactivation queue renders only the branch's existing shopPhoto/signboardPhoto slots, but the fresh reactivation evidence photo (the one that must pass the >=24h + captured-after-lastStatusChange gate) is captured as a FREE photo wired to branchExtraId and recorded in edit.attachmentChanges — it is NEVER written to those slots, so the reviewer never sees it. The whole QA-008/EL-11/EL-12 fresh-evidence hardening is invisible to the human who actually decides the reactivation.

**Evidence:** BranchStatusActions.tsx:110-116 captures the reactivation evidence with slot 'FREE' (attachTo={kind:'branch',branchId,slot:'FREE'}). photos.ts:239-244 routes slot FREE to `branchExtraId:b.id, branchId:b.id, kind:FREE` and never touches shopPhotoId/signboardPhotoId. reactivations.ts:126-128 stores the same attachment id in `attachmentChanges` as action 'EVIDENCE'. reactivations/page.tsx:30-46 include{} loads only branch.shopPhotoId/signboardPhotoId (never attachmentChanges or the branchExtra photos), and lines 83-98 render only `e.branch.shopPhotoId` / `e.branch.signboardPhotoId`. So the served <img> tags point at the branch's OLD slot photos (or render nothing when those slots are empty), not the just-captured evidence.

**Scenario:** A CLOSED branch whose shopPhoto slot still holds the pre-closure/closed-shop photo. Salesman visits the reopened shop, captures a fresh FREE photo (passes the server-side freshness gate), and submits the reactivation. The Manager opens /reactivations and sees the STALE closed-shop photo (or an empty grid). They may wrongly reject the legitimate reactivation because the displayed photo shows a closed shop, or approve without ever seeing the verification the workflow was built to require. Freshness is still enforced at submit, so this is review-quality/decision harm, not data corruption or an authz bypass.

## [13] P2 <fresh-eyes> — Branch completeness (0-60 scale) rendered as a 0-100% ring/bar — branches & regions can never reach 'high'/green, and the dashboard mixes two scales
**File:** `components/nmwc/CompletenessRing.tsx:27`

**Claim:** scoreBranch() maxes at 60 points (15 GPS + 5 address + 10 shop + 10 signboard + 5 day + 5 equipment + 5 hours + 5 status = 60; lib/completeness.ts:51-70 states 'out of 60'), and branch.completenessScore is stored verbatim on that 0-60 scale. But CompletenessRing treats its `value` as a 0-100 percentage — it clamps to [0,100], draws the arc as pct/100, and colours via completenessBand(pct) whose 'high' band requires >=80 (lib/completeness.ts:91-95). It is fed the raw branch score at app/(app)/customers/[id]/page.tsx:149 (`value={b.completenessScore}`). Consequently a *fully* complete branch (60/60) renders as the number '60', a 60%-filled arc, and the amber 'medium' band — a branch can NEVER show green, and never shows 100. The same 0-60 branch scores are averaged and rendered as percentages on the dashboard: 'Completeness by region' colours bars with `avg>=80?green:avg>=50?amber:red` and sets width `${avg}%` (app/(app)/dashboard/page.tsx:208-224), and the per-route leaderboard averages branch scores (app/(app)/dashboard/page.tsx:127-135). Because branch averages cannot exceed 60, every regional/route completeness bar is capped at 60% width and can never be green. Worse, the SAME dashboard's 'Avg completeness' KPI (dashboard/page.tsx:173) and the customer-detail/CustomerCard/duplicates rings all use the customer-level score which IS 0-100 (scoreCustomer = customerPart 0-40 + branchPart 0-60) — so the app renders 0-100 and 0-60 numbers side-by-side as if both were percentages.

**Evidence:** lib/completeness.ts:51-70 scoreBranch returns max 60 ('out of 60'); lib/completeness.ts:91-95 completenessBand needs >=80 for 'high'; components/nmwc/CompletenessRing.tsx:23-27,59 clamps to 100, arc=pct/100, band=completenessBand(pct), prints pct; app/(app)/customers/[id]/page.tsx:149 passes raw branch score to the ring; app/(app)/dashboard/page.tsx:219 colours region bar avg>=80?green:avg>=50?amber (branch-score average, so >=80 unreachable) and 221 width `${avg}%`; app/(app)/dashboard/page.tsx:129-134 route leaderboard averages branch scores. No normalization (score*100/60) exists anywhere between store and render.

**Scenario:** A steward opens a customer whose branch has GPS, address, both photos, day-of-visit, equipment counts, hours and ACTIVE status — every field populated. The branch ring shows '60' in amber, implying the branch is only 60% complete and flagged for attention, so the steward chases data that is already complete. On the dashboard, a region composed entirely of such perfect branches shows a 60%, amber 'Completeness by region' bar that can never turn green — directly undermining the manager's 'which routes need attention' read that the UXI-018 comment (dashboard/page.tsx:123-126) says the chart exists to provide. Stored data is correct; this is display/reporting-only, but it is systematic across the branch ring, the region chart, and the route leaderboard.

## [14] P2 <regressions> — Customer-master re-import upsert bypasses the B-05 optimistic lock (no version bump) — silent lost update vs a concurrent edit-approve
**File:** `services/imports.ts:1078`

**Claim:** In promoteCustomerBatchCore, the NON-refresh customer upsert UPDATE path (lines 1078-1089) and the branch upsert UPDATE path (lines 1145-1154) write master fields (legalName, primaryPhone/Norm, contactPerson, crNumber/Norm, paymentTerms; branch address/region/route/name) WITHOUT `version: { increment: 1 }`. This violates the schema's own B-05 invariant (prisma/schema.prisma:303-305: "Service layer increments on every UPDATE and includes `version` in the WHERE clause") and is inconsistent with the sibling Temix-refresh path in the same function, which was deliberately given `version: { increment: 1 }` at line 1056 with the comment "make the refresh visible to the optimistic lock so a concurrent edit-approve sees VERSION_CONFLICT, not a silent revert." The plain-import path never got the same treatment.

**Evidence:** imports.ts:1078-1089 (upsert update: no version increment) and imports.ts:1145-1154 (branch upsert update: no version increment), contrasted with the refresh path imports.ts:1053-1057 which does `version: { increment: 1 }` explicitly for this exact reason. applyEditChanges (services/edits.ts:612-625, 649-652) relies on the version column to fail closed with VERSION_CONFLICT. Re-import of an existing customer is a supported, reachable path: uploadCustomerMasterCore keys phone/CR collision detection by owning nmwcCode so a customer's own re-import row is NOT quarantined (imports.ts:602-666), lands CLEAN, and promotes through the upsert UPDATE branch.

**Scenario:** A Steward re-imports a corrected customer master (updating e.g. primaryPhone/contactPerson) while a Supervisor concurrently approves an in-flight salesman enrichment edit touching the same field on the same customer. The edit-approve reads version V; the import commits its field write without bumping V; the edit-approve's version-checked updateMany still matches V, applies, and increments to V+1. The import's correction to the shared field is silently overwritten (or vice-versa) with NO VERSION_CONFLICT surfaced. Overlap is on salesman-editable columns (primaryPhone, contactPerson, altPhone, channelId, notes). Low probability (imports are infrequent and Steward-scheduled) but the loss is silent and there is no detection/workaround — the very failure mode the optimistic lock exists to prevent.

## [15] P2 <approval-engine> — RK-2 wedge still open: CREATE approval visibility scopes on FROZEN draft region while the approve gate/escalation/finalize scope on CURRENT route region — a mid-chain route re-region strands the request at the Accountant step
**File:** `(app)/approvals/page.tsx:74`

**Claim:** For process=CREATE edits, the authoritative approve/reject authorization, the SLA-escalation sweep, and finalize all derive region scope from the CURRENT route (edit.branchDrafts[].route.regionId), but the approval queue, the approval detail page, the home 'work' queue, and the CREATE-photo access check all derive region scope from the FROZEN EditBranchDraft.regionId snapshot taken at submit. These are equal at submit (enforced by the editbranchdraft_region_consistency_check trigger) but diverge permanently if a Steward re-regions the route mid-chain (a scenario create-finalize.ts:96-101 explicitly anticipates). The result: a SUBMITTED CREATE request that reaches the region-scoped ACCOUNTANT step (final step of both CASH SUP->ACC and CREDIT SUP->FM->GM->ACC chains) becomes unactionable by any user via the UI — the correct current-region Accountant can neither see it in their queue nor open its detail page (both gate on the frozen region and 404/omit it), while the stale frozen-region Accountant sees it in the queue but is rejected by the approve gate (ForbiddenError, because canActOnStep REGION_OVERLAP evaluates the CURRENT route region). The submitter's direct Supervisor step is unaffected (it authorizes on submittedBy.supervisorId with no region gate) and FM/GM are org-wide, so a CREDIT request can burn all its finance approvals and only then dead-end at finalize. No data corruption and no wrong-approval/security bypass (the approve gate correctly uses the region where the customer will materialize); this is a liveness/stranding defect.

**Evidence:** Authoritative approve gate uses CURRENT region: services/edits.ts:758-761 `scopeBranches = isCreate ? edit.branchDrafts.map((d) => ({ regionId: d.route.regionId, deletedAt: null })) : ...` feeding canActOnStep (permissions.ts:194-203 REGION_OVERLAP requires managed.includes(b.regionId)). Reject path identical: services/edits.ts:1309-1312. SLA escalation uses CURRENT region: app/api/cron/sla-escalate/route.ts:76 `e.branchDrafts.map((b) => b.route.regionId)`. Finalize materializes in CURRENT route region: lib/create-finalize.ts:102-116,213. In contrast, every visibility surface uses the FROZEN EditBranchDraft.regionId: queue app/(app)/approvals/page.tsx:74 `branchDrafts: { some: { regionId: { in: scope.managedRegionIds } } }`; detail app/(app)/approvals/[id]/page.tsx:84-88 `regionIds = isCreate ? edit.branchDrafts.map((b) => b.regionId) : ...; if (!inScope) notFound()`; home work queue app/(app)/work/page.tsx:147 and 196; CREATE-photo access lib/access.ts:242-244 `regionId: d.regionId`. Schema confirms both fields coexist on the draft (prisma/schema.prisma:642-666: EditBranchDraft has frozen `regionId` AND `routeId` with a `route` relation), and the consistency trigger fires only on draft INSERT/UPDATE (migration 20260715120100:250-253), so a later Route.regionId change is never propagated to the frozen draft.regionId. Fix: make the four visibility surfaces resolve region through the draft's route (route.regionId) so they match the approve gate, escalation, and finalize.

**Scenario:** A salesman submits a CREDIT create request; branches are on route R (region A at submit, so draft.regionId=A). Direct Supervisor approves (step 0, no region gate). FM and GM approve (org-wide). Before the Accountant acts, a Steward import re-regions route R from A to B. Now route.regionId=B but draft.regionId=A. The region-B Accountant's /approvals queue and /work queue filter branchDrafts.regionId in [B] -> row absent; a deep link to /approvals/<id> hits the detail gate at [id]/page.tsx:87 (frozen A not in [B]) -> notFound. The region-A Accountant sees the row in their queue, clicks approve, and approveEditCore computes scopeBranches from route.regionId=B; canActOnStep REGION_OVERLAP finds [B] does not overlap managed=[A] -> ForbiddenError 'You are not authorized to act on this step.' The credit customer is now permanently stuck at the final step with no UI actor, until someone re-regions R back to A, or a Steward/GM notices the SLA breach and intervenes, or the request is rejected and resubmitted (resubmit refreshes draft.regionId via createMany in creates.ts:410).

## [16] P2 <concurrency> — Reactivation & close-shop submits collide with CustomerEdit_open_per_customer index — opaque, unrecoverable UNIQUE_CONSTRAINT dead-end
**File:** `services/reactivations.ts:104`

**Claim:** requestReactivationCore (line 104) and markBranchClosedCore (line 208) do a bare `prisma.customerEdit.create({ customerId: branch.customerId, state: SUBMITTED, ... })` with NO P2002 handling. The partial-unique index `CustomerEdit_open_per_customer` ON (customerId) WHERE state='SUBMITTED' AND customerId IS NOT NULL (prisma/migrations/20260509150000_qa_remediation/migration.sql:12) has no target/isReactivation filter, so it permits only ONE submitted CustomerEdit per customerId across ALL workflows. Whenever a customer already has any other pending SUBMITTED edit (an enrichment edit, or a close/reactivation on a DIFFERENT branch), the reactivation/close INSERT deterministically raises P2002. Because these cores lack the P2002->ConflictError translation that the enrichment path has, runAction falls through to the generic branch and returns { code:'UNIQUE_CONSTRAINT', message:'This value conflicts with an existing record. Refresh and try again.' } (lib/errors.ts:140-146) — a non-actionable dead-end that refreshing never clears.

**Evidence:** services/reactivations.ts:104-130 and :208-231 are plain creates with customerId=branch.customerId + state=SUBMITTED and no try/catch. services/edits.ts:522-538 shows the P2002->EDIT_LOCKED translation the enrichment path DOES have (and edits.ts:291-301 also pre-checks findFirst({customerId,state:SUBMITTED})). The index def (WHERE state='SUBMITTED' AND customerId IS NOT NULL, no target filter) is at prisma/migrations/20260509150000_qa_remediation/migration.sql:12-14. NMWC customers routinely have many branches (see services/duplicates.ts:41-45 'one owner runs many shops'), so two independent branch operations, or an enrichment edit + a branch closure, on the same customer are mutually exclusive and the loser gets a confusing error.

**Scenario:** Customer C has branches B1 (just closed) and B2. A salesman has a pending SUBMITTED enrichment edit on C (fixing a phone) awaiting supervisor approval. The salesman files a close request for B1 -> customerEdit INSERT hits CustomerEdit_open_per_customer (state SUBMITTED, same customerId) -> P2002 -> user sees 'This value conflicts with an existing record. Refresh and try again.' Refreshing does nothing; the close is blocked until the unrelated enrichment edit is approved/rejected. Same happens for a reactivation, and for two branches of one customer both needing close/reactivation.

## [17] P2 <authz-idor> — Manager direct-write edit authorizes branch writes at customer-level, not per-branch region — cross-region branch tamper
**File:** `services/edits.ts:381`

**Claim:** submitEditCore gates a MANAGER's direct-write on assertCanEditCustomer (customer-level, ANY-branch-region-overlap) but then applies branch-field writes to whatever branchId is passed with NO per-branch region check. The salesman path is per-branch route-scoped at line 381; the Manager path has no equivalent, so a Manager can direct-write operational fields (address, GPS, dayOfVisit, coolers/stands/empties, non-status branch data) on a branch located in ANOTHER manager's region as long as the multi-region customer has at least one branch in the acting Manager's region. This is the same 'any-branch-overlap is not authority over the whole customer' hole that archiveCustomerCore explicitly closed (customers.ts:60-68 requires EVERY live branch in-region for a Manager) — the SEC-H1 fix on this write path stopped at customer scope and never reached per-branch scope. The identical root cause exists in the photo path: attachPhotoCore's branch attach (services/photos.ts:198-207) authorizes a MANAGER via assertCanEditCustomer on b.customer, so a Manager can attach to — and destructively soft-delete the existing shop/signboard photo of — an out-of-region sibling branch of an in-scope customer.

**Evidence:** edits.ts:271-285 the only MANAGER gate is `assertCanEditCustomer(...customer...)` which resolves to canSeeCustomer → `customer.branches.some(b => managedRegionIds.includes(b.regionId))` (access.ts:89-102) i.e. ANY branch overlap. edits.ts:376-383 branch loop: `if (me.role === Role.SALESMAN && me.ownedRouteId && branch.routeId !== me.ownedRouteId) throw` — no MANAGER case; branchById only requires the branch to belong to the customer (any region). edits.ts:475 isDirectWrite true for MANAGER → applyEditChanges (edits.ts:629-659) writes each bp.branchId with only an optimistic-version check, no scope check. Contrast customers.ts:60-68 which for the whole-customer archive requires `liveBranches.every(b => scope.managedRegionIds.includes(b.regionId))`.

**Scenario:** Multi-region customer (e.g. a national chain) has branch A in Muscat and branch B in Dhofar. Manager_Muscat (managedRegions=[Muscat]) POSTs submitEditAction with customerId=chain and branches=[{branchId: B, address/gps/dayOfVisit...}]. assertCanEditCustomer passes (branch A is in Muscat). Branch loop skips the salesman check; applyEditChanges overwrites Dhofar branch B's operational data with reviewedById=Manager_Muscat. Mitigation lowering severity: branch B's cuid is not exposed to Manager_Muscat through scoped UI/exports (all filter by region), so discovery of the out-of-region branchId is the practical barrier — but relying on ID secrecy for object-level authorization is the defect. Fix: in the MANAGER branch loop (and attachPhotoCore branch path) assert `scope.managedRegionIds.includes(branch.regionId)` per branch, or filter branchesPayload through filterBranchesByScope before write.

## [18] P2 <authz-idor> — GUARANTEE credit documents are browser-cacheable (60s) — CR-only no-store guard never extended to the newer GUARANTEE kind
**File:** `photos/[id]/route.ts:69`

**Claim:** The photo-streaming endpoint sets `Cache-Control: private, no-store, no-cache, must-revalidate` ONLY when `att.kind === 'CR'`; every other kind (including GUARANTEE) gets `private, max-age=60, must-revalidate`. GUARANTEE attachments are the credit-guarantee / security documents captured on net-new CREATE-CREDIT requests (presign/route.ts:19-21) — guarantor identity/financial collateral, at least as sensitive as a CR document. They are served through this same [id] endpoint and rendered on the FM/GM/Accountant credit-review pages (approvals/[id]/page.tsx:125-128, customers/new/page.tsx:53). Because the CR no-store special-case was written before GUARANTEE existed and never updated, a guarantee document lands in the viewer's browser cache for 60s and is served from cache on Back/re-navigation WITHOUT a fresh server-side scope check — the exact shared-device PII exposure the CR no-store rule (NEW-PHOTO-009) was created to prevent.

**Evidence:** app/api/photos/[id]/route.ts:67-71 — `const cache = att.kind === 'CR' ? 'private, no-store, no-cache, must-revalidate' : 'private, max-age=60, must-revalidate';`. GUARANTEE falls into the else branch. Grep of app/ for cache/no-store shows the only kind-based cache decision is this single `att.kind === 'CR'` check; GUARANTEE appears in presign enum, finalize kindFromKey regex, and the credit-review pages, but never in the cache-control decision.

**Scenario:** On a shared NMWC workstation an Accountant reviews a CREDIT customer's guarantee doc (rendered <img src=/api/photos/{id}>), then logs out. Within 60s another user on the same browser presses Back or reopens the tab; the guarantee image is served from the browser's private cache (fresh under max-age=60, no revalidation, no session/scope recheck), exposing guarantor PII/financial collateral to an unauthorized viewer. Fix: treat GUARANTEE like CR — `att.kind === 'CR' || att.kind === 'GUARANTEE'` → no-store.

## [19] P2 <temix> — Plain customer-master re-import silently downgrades existing CREDIT customers to CASH when the payment_terms column is absent (F-12 gate not applied to the full-upsert lane)
**File:** `services/imports.ts:1082`

**Claim:** The F-12 fix introduced paymentTermsPresent (imports.ts:675-682) to distinguish 'column absent — keep current terms' from 'explicit CASH', but it is honored ONLY in the Temix-refresh branch (imports.ts:1033-1039). The plain upsert UPDATE path writes `paymentTerms: pt` unconditionally (imports.ts:968 sets pt = first.paymentTerms==='CREDIT' ? 'CREDIT' : 'CASH', defaulting to CASH when the column is absent; imports.ts:1082 applies it), so re-importing an existing CREDIT customer through a sheet lacking payment_terms (and lacking temix_code, so isRefresh is false) silently flips it to CASH.

**Evidence:** The UPDATE block (imports.ts:1080-1089) sets paymentTerms=CASH but does NOT touch creditLimit/paymentTermDays, producing an inconsistent CASH record that retains a stale creditLimit/paymentTermDays and silently loses its credit designation (and, via lib/temix.ts:85-96, the next outbound Temix row would then emit CASH with blank credit). No quarantine or warning is raised. The F-12 comment explicitly states 'Legacy create/full-upsert paths keep the CASH default unchanged', so this gap is acknowledged but left — the same absent-column footgun F-12 called an 'adversarial-review CONFIRMED finding' remains live in the full-upsert lane, which is the lane a plain (non-temix_code) re-import always takes. The standard export includes payment_terms (services/exports.ts:137), so full round-trips are safe; the risk is a hand-crafted / partial correction sheet.

**Scenario:** Steward imports a partial correction sheet for existing customers (e.g. fixing addresses or phones for 50 records) that omits the payment_terms column and has no temix_code. Every existing CREDIT customer in that sheet is silently downgraded to CASH with a stale, now-orphaned creditLimit — credit terms lost with no error.

## [20] P2 <data-integrity> — detachPhoto soft-deletes photo but never recomputes completenessScore → permanent rollup drift
**File:** `services/photos.ts:325`

**Claim:** detachPhotoCore nulls the completeness-bearing slot pointer (crPhotoId / shopPhotoId / signboardPhotoId) and soft-deletes the Attachment, but its transaction (services/photos.ts:325-357) never calls scoreCustomer/scoreBranch to update the stored completenessScore. This is the ONLY completeness-affecting mutation path that omits the recompute — the attach path recomputes at services/photos.ts:168 (customer), :247 (branch) and :254 (customer), and edits.ts:666-669, duplicates.ts:324, reactivations.ts:322-328, imports.ts:1182 and create-finalize.ts:312-313 all recompute too. The omission is a regression from the photo soft-delete rewrite (NEW-PHOTO-002 added the slot-blanking to detach; NEW-PHOTO-003 added the recompute only to attach).

**Evidence:** lib/completeness.ts scores crPhotoId (+10, line 46), shopPhotoId (+10, line 55) and signboardPhotoId (+10, line 56). lib/customer-filters.ts:192-195 puts the stored completenessScore directly into the list/export WHERE clause (minScore→gte, maxScore→lte); it is also read by exports and the completeness dashboards (dashboard/today/duplicates pages). detachPhotoCore transaction at services/photos.ts:326-341 nulls the slot and :344-347 soft-deletes, then :348-356 writes the audit row and returns — no scoreCustomer/scoreBranch call anywhere in the function.

**Scenario:** A salesman/steward removes a customer's CR photo (or a branch's shop/signboard photo) via detachPhotoAction. The photo is gone and the slot pointer is null, but the customer's completenessScore stays 10 points too high permanently (until some unrelated future edit happens to recompute it). That customer now: (a) still passes a `minScore=80` "high completeness" filter it should have dropped out of, (b) exports with an overstated score, and (c) is under-counted in the "needs data completion" dashboards — exactly the operational signal completenessScore exists to drive.

## [21] P3 <regressions> — Stale workweek docstrings contradict the Sun–Thu default after the WORK_DAYS fix
**File:** `lib/working-hours.ts:16`

**Claim:** The WORK_DAYS default was changed to '0,1,2,3,4' (Sun–Thu; Fri AND Sat off), but two docstrings in the same file still describe Saturday as a working day / Friday as the only day off, directly contradicting the corrected comment three lines below and the code. No runtime effect, but it misleads any maintainer reasoning about the SLA calendar.

**Evidence:** lib/working-hours.ts:16 states 'Defaults: Sun–Thu + Sat working (Friday off — OLD parity)', and :90-91 states 'A submission at 16:30 Thursday with a 60-minute budget is due 08:30 Saturday (Friday off)'. Both contradict :21-24 (correct: default '0,1,2,3,4', 'Fri (5) AND Sat (6) are off') and the actual code path isWorkDay()/WORK_DAYS at :69-70. With the current default, a Thursday-16:30 submission is due Sunday 08:30, not Saturday.

**Scenario:** A future maintainer tuning SLA behavior reads line 16/91, believes Saturday is a working day, and mis-sizes an env override or a test fixture for the escalation cron — the same class of stale-assumption bug the f1d0505 fixture fix already had to correct once.

## [22] P3 <concurrency> — EL-04 approve-time mandatory-photo gate is a TOCTOU (read outside the approve tx, never re-asserted inside)
**File:** `services/edits.ts:1062`

**Claim:** The FINAL-UPDATE approve path re-checks mandatory fields/photos against the LIVE customer with a plain `prisma.customer.findUniqueOrThrow` at line 1062, OUTSIDE the transaction that is opened at line 1084. Inside that tx, applyEditChanges only re-applies fieldChanges + recomputes completeness; it never re-runs collectMissingMandatory. A concurrent detachPhoto that soft-deletes the CR/shop photo (detachPhotoCore sets crPhotoId=null WITHOUT bumping Customer.version, so the optimistic lock in applyEditChanges does NOT catch it) between the line-1062 read and the tx claim lets the UPDATE be approved onto a customer that just lost a mandatory photo — the exact outcome EL-04 was written to block. The create flow closes this same TOCTOU in-tx via guarded updateMany binds (lib/create-finalize.ts step 6, bindOne); the UPDATE approve path does not, so the fix is inconsistent/incomplete.

**Evidence:** services/edits.ts:1061-1082 performs `const liveCustomer = await prisma.customer.findUniqueOrThrow(...)` and `collectMissingMandatory(...)` then throws NEEDS_REUPLOAD, all before `await prisma.$transaction(async (tx) => {` at line 1084. detachPhotoCore (services/photos.ts:325-347) clears crPhotoId via updateMany with no version increment, so applyEditChanges' versioned updateMany (services/edits.ts:616-626) still matches version and commits.

**Scenario:** Salesman submits an UPDATE on customer C (C has crPhotoId=P0). Approver invokes approve; EL-04 read at line 1062 sees P0 present → passes. In the few-ms window before the tx claim, the salesman detaches P0 (crPhotoId→null, P0 soft-deleted). approve tx claims the edit, applies field changes, recomputes completeness (now lower), commits APPROVED. Result: an approved customer master row with no CR photo — non-silent (completeness drops, slot shows empty) but the mandatory-photo invariant EL-04 enforces is violated.

## [23] P3 <concurrency> — Import promote can strand a batch permanently in PROMOTING (claim has no compensating release on early failure)
**File:** `services/imports.ts:822`

**Claim:** promoteCustomerBatchCore atomically claims the batch READY→PROMOTING (lines 774-777) but then does un-guarded work before the per-group try/catch: it reads cleanRows (787) and lazily creates the UNASSIGNED region+route (822-833). region.code and route.code are @unique, so when two customer batches are promoted concurrently and both need UNASSIGNED for the first time, the second `prisma.region.create`/`prisma.route.create` throws P2002. That throw is OUTSIDE the per-group try/catch (which starts at line 965), so it escapes promoteCustomerBatchCore; runAction returns a generic UNIQUE_CONSTRAINT, but the batch is left in PROMOTING. There is no code path that resets PROMOTING→READY (the promote claim only matches status='READY'), so the batch is non-recoverable without manual DB surgery. Any transient error in this pre-loop region (not just the UNASSIGNED race) strands the batch the same way.

**Evidence:** services/imports.ts:774-777 sets status PROMOTING; 822-833 does findUnique-then-create on UNASSIGNED region/route with no try/catch; the per-group `try {` guard only begins at line 965; the terminal `importBatch.update status:'PROMOTED'` is at line 1246. grep confirms the only status transition into READY is the parse step (line 753) and the only promote claim is `where: { id, status:'READY' }` (line 775) — no PROMOTING→READY recovery exists.

**Scenario:** Two Stewards (or one Steward on two batches) promote concurrently on a fresh DB where UNASSIGNED has never been created, and both batches contain rows with missing/unknown routes. First promote creates UNASSIGNED; second promote's region.create/route.create hits P2002, the exception escapes, and its batch stays PROMOTING forever — the Steward can never re-promote it via the UI.

## [24] P3 <concurrency> — Branch close / reactivation submit surfaces a raw P2002 (generic conflict) when the customer already has any pending SUBMITTED edit
**File:** `services/reactivations.ts:208`

**Claim:** The partial unique index CustomerEdit_open_per_customer keys only on customerId WHERE state='SUBMITTED' AND customerId IS NOT NULL. Branch-target edits (markBranchClosedCore and requestReactivationCore) set BOTH branchId and customerId, so they also count against the per-customer limit. When the customer already has any open SUBMITTED edit (a customer-level enrichment edit, or a close/reactivation on a different branch of the same customer), the `prisma.customerEdit.create` in these two actions throws P2002, which neither action catches. runAction translates it into the generic 'This value conflicts with an existing record. Refresh and try again.' submitEditCore handles the symmetric case cleanly (pre-checks and throws EDIT_LOCKED with an actionable message, services/edits.ts:291-301), so the close/reactivation paths are inconsistent: the salesman gets an unactionable error and cannot record a genuine shop closure/reopening until the unrelated pending edit is approved.

**Evidence:** services/reactivations.ts:104-130 (requestReactivationCore) and :208-231 (markBranchClosedCore) both do a bare `prisma.customerEdit.create({ data: { branchId, customerId: branch.customerId, state: SUBMITTED, ... } })` with no P2002 handling. prisma/migrations/20260509150000_qa_remediation/migration.sql:12-14 defines the index on customerId only. lib/errors.ts:140-147 converts an untranslated P2002 to the generic UNIQUE_CONSTRAINT message.

**Scenario:** Customer C has a SUBMITTED customer-level edit pending review. The salesman (or another salesman on a co-owned branch route) tries to mark a branch of C CLOSED. The insert violates CustomerEdit_open_per_customer → generic 'conflicts with an existing record' error. Refreshing does not clear the unrelated pending edit, so the closure cannot be recorded until that edit is approved — safe (no corruption) but confusing and blocks a legitimate operational action.

## [25] P3 <data-integrity> — routes.ts region/route mutations never revalidate ref-data cache tags
**File:** `services/routes.ts:72`

**Claim:** createRegionCore, createRouteCore, toggleRegionActiveCore and toggleRouteActiveCore only call revalidatePath('/routes') (lines 72, 98, 123, 148). None calls revalidateTag('ref:regions') or revalidateTag('ref:routes'), which the reference-data cache explicitly requires.

**Evidence:** lib/reference-data.ts documents the contract in its header (lines 17-19): 'Mutating services (e.g. routes/users when a manager onboards a salesman) should call revalidateTag(\'ref:routes\') after the write.' getAllActiveRegions and getAllActiveRoutes are unstable_cache-wrapped with tags ['ref:regions']/['ref:routes'] and revalidate = 5*60 seconds (lib/reference-data.ts lines 41, 47-54, 62-69). grep confirms services/routes.ts contains zero revalidateTag calls. These cached lookups populate the region/route dropdowns used in the create-customer and route-assignment forms.

**Scenario:** A Manager creates a new Region or Route (or toggles one inactive). Because only the /routes path is revalidated and the ref:regions/ref:routes tags are not, the cached dropdown data served to create-customer / assignment forms stays stale for up to 5 minutes: a just-created route does not appear (so a salesman can't be assigned to it), and a just-disabled route still appears and remains selectable. Self-heals after the 5-minute TTL, so low harm, but it violates the documented cache-invalidation contract that users.ts-style mutators are expected to honor.

## [26] P3 <edge-null> — working-hours.ts module docstring contradicts the owner-confirmed Sun–Thu default
**File:** `C:\Users\abdulr\Desktop\NMWC-CRM\.claude\worktrees\nmwc-crm-consolidation-e10c1e\lib\working-hours.ts:16`

**Claim:** The module header comment states the default is 'Sun–Thu + Sat working (Friday off — OLD parity)', i.e. Saturday is a working day. The actual WORK_DAYS default is '0,1,2,3,4' (Sun–Thu only; both Fri=5 and Sat=6 off), matching the owner-confirmed 5-day week and the correct inline comment 20 lines below. Runtime behavior (slaDeadline/workingMinutesBetween correctly skip Saturday) is right; only the top-of-file documentation is stale and directly contradicts the code and its own later comment.

**Evidence:** working-hours.ts:16-17 says 'Defaults: Sun–Thu + Sat working (Friday off — OLD parity)'. working-hours.ts:21-24 sets WORK_DAYS = Set('0,1,2,3,4'.split...) with the correct comment 'Owner-confirmed workweek is Sun–Thu (5-day); Fri (5) AND Sat (6) are off.' isWorkDay() at line 69-71 keys off this Set, so Saturday is correctly excluded — the header comment is the only wrong artifact.

**Scenario:** An operator reading the module header to decide whether to override WORK_DAYS (or reasoning about SLA due-dates that land on a Saturday) is told Saturday counts as a working day, when in fact SLA clocks skip it. Misleads maintenance/ops; no runtime impact.

## [27] P3 <fresh-eyes> — Customer NMWC code year derived from UTC (getFullYear) while all SLA logic uses Oman wall-clock — prior-year code prefix in the 00:00-03:59 Oman window of Jan 1
**File:** `lib/create-finalize.ts:175`

**Claim:** allocateCustomerCode is called with finalizedAt.getFullYear(). finalizedAt is `new Date()` created inside approveEditCore (services/edits.ts:873) and getFullYear() resolves against the server's local zone — UTC on Vercel. Every other time-of-day computation in the codebase deliberately shifts to Asia/Muscat wall-clock (UTC+4, TZ_OFFSET_MIN=240) precisely because the OLD system's bug was using server-local/UTC fields (lib/working-hours.ts:1-20). The code year was not given the same treatment, so for finalizes occurring between 00:00 and 03:59 Oman time on 1 January, UTC is still 31 December of the prior year and getFullYear() returns the prior year: the customer is stamped NMWC-<prior-year>-NNNNNN and consumes a CodeSequence number under scope CUSTOMER-<prior-year>. No collision or corruption results (the sequence is still atomic and unique), but the human-readable year embedded in the permanent customer code (codes.ts:9-11) is wrong for a customer that was, in Oman civil time, created in the new year.

**Evidence:** lib/create-finalize.ts:175 `allocateCustomerCode(tx, finalizedAt.getFullYear())` — no Oman-offset applied; lib/working-hours.ts:20,49-71 shows the codebase's established Oman wall-clock convention (getUTC* on a +240min shifted Date) used for all SLA date math; lib/codes.ts:9-11 embeds `year` literally into NMWC-YYYY-NNNNNN.

**Scenario:** An Accountant gives final CREATE approval at 01:30 on 1 Jan 2027 Oman time (= 21:30 on 31 Dec 2026 UTC). getFullYear() returns 2026, so the new customer is issued NMWC-2026-000123 and advances the CUSTOMER-2026 counter, despite being created in Oman-civil-2027. The code's year is off by one for any finalize in that ~4-hour post-midnight window at a year boundary.

## [28] P3 <regressions> — working-hours.ts docstrings still describe the OLD Sat-working / Fri-off week after the workweek was changed to Sun–Thu
**File:** `lib/working-hours.ts:16`

**Claim:** The module header (lines 16-17) states "Defaults: Sun–Thu + Sat working (Friday off — OLD parity), 08:00–17:00 Oman" and the slaDeadline docstring (lines 91-93) gives the worked example "A submission at 16:30 Thursday with a 60-minute budget is due 08:30 Saturday (Friday off)". Both are now wrong: the owner-confirmed workweek is Sun–Thu with BOTH Friday AND Saturday off, and the actual code default was correctly changed to WORK_DAYS='0,1,2,3,4' (lines 21-24). The stale comments directly contradict the live behavior.

**Evidence:** lib/working-hours.ts:16-17 and 91-93 (stale Sat-working text and Saturday due-date example) vs the corrected default and accurate note at lib/working-hours.ts:21-24 ("Owner-confirmed workweek is Sun–Thu (5-day); Fri (5) AND Sat (6) are off"). With WORK_DAYS excluding 6, a 16:30-Thursday +60m budget is actually due ~08:30 Sunday, not Saturday.

**Scenario:** An operator tuning WORK_DAYS or reasoning about SLA deadlines reads the header/example, believes Saturday is a working day, and mis-sets the env var or mis-diagnoses an escalation timing — no runtime defect, but a documentation trap in the exact area the workweek fix touched.

## [29] P3 <regressions> — CreateUserForm offers approver/admin roles that the Manager-only createUserAction always rejects (SR-USR-01 allowlist not reflected in the UI)
**File:** `(app)/users/CreateUserForm.tsx:69`

**Claim:** The role <select> renders all 8 roles from ROLE_LABELS (lines 7-16, 69-73), including ACCOUNTANT, FINANCE_MANAGER, GM, MANAGER and STEWARD. But the /users page is Manager-only (app/(app)/users/page.tsx:14) and createUserAction runs requireManager() then rejects any role outside MANAGER_ADMINISTRABLE_ROLES (SALESMAN/SUPERVISOR/VIEWER) at services/users.ts:83-88. So every approver/admin option a Manager can pick is guaranteed to fail server-side. The UI was not updated to match the SR-USR-01 allowlist fix.

**Evidence:** CreateUserForm.tsx:7-16 (ROLE_LABELS lists all 8) and 62-74 (renders every entry, no role gating); server rejection at services/users.ts:83-88; page gate at app/(app)/users/page.tsx:14 (redirect unless MANAGER). MANAGER_ADMINISTRABLE_ROLES = [SALESMAN, SUPERVISOR, VIEWER] at lib/permissions.ts:223-227.

**Scenario:** A Manager selects "Accountant"/"Finance Manager"/"GM" to staff the credit-approval chain, fills the form, and always gets a validation error. The server is safe (defense-in-depth intact), but the form presents unreachable options — a confusing dead-end that contradicts the allowlist the fix established. Purely UX; no security impact.

## [30] P3 <import-promote> — In-group branch_code dedup rejects Temix-refresh groups that never write branches
**File:** `services/imports.ts:945`

**Claim:** The per-customer duplicate-branchCode guard (imports.ts:939-963) runs BEFORE the transaction determines isRefresh (computed at imports.ts:1018). Branch upserts are gated by `if (!isRefresh)` (imports.ts:1111), and region/route resolve warnings are already suppressed for refresh rows (imports.ts:1187 `!refreshedRow`), but the dedup REJECT at imports.ts:945-963 has no such guard. So a Temix-refresh group (temix_code present) whose rows resolve to the same branchCode is rejected outright even though its branches are deliberately never touched — the crosswalk/credit refresh for that customer is silently dropped to REJECTED.

**Evidence:** imports.ts:939-944 builds seenBranchCodes and sets dupBranchCode across resolvedBranches, then imports.ts:945-963 pushes a failure and marks the whole group REJECTED with `continue` — all before the try/tx at imports.ts:965. isRefresh (and thus 'branches will be skipped') is only known at imports.ts:1018 inside the tx. Compare imports.ts:1187 where groupResolveErrors are explicitly skipped for refresh rows, showing the code elsewhere knows refresh rows must not be penalized for branch data.

**Scenario:** An existing multi-branch customer is refreshed with a sheet carrying temix_code + credit figures repeated on each of its rows, where two rows share (or omit, colliding via positional formatBranchCode) the same branch_code. resolvedBranches collide, dupBranchCode is set, and the group is REJECTED at imports.ts:945 — so the Temix code/credit refresh never applies, despite branches being irrelevant to a refresh.

## [31] P3 <concurrency> — mergeCustomersCore moves ALL loser edits to winner and can violate open_per_customer, aborting the whole merge with an opaque error
**File:** `services/duplicates.ts:272`

**Claim:** The merge transaction runs `tx.customerEdit.updateMany({ where:{ customerId: loser.id }, data:{ customerId: winner.id }})` unconditionally moving every CustomerEdit (regardless of state) onto the winner. If the loser has an open SUBMITTED edit (enrichment, reactivation, or close) AND the winner also has one, the update produces two rows with customerId=winner AND state=SUBMITTED, violating the CustomerEdit_open_per_customer partial-unique index. The updateMany raises P2002, the whole merge $transaction rolls back, and (with no P2002 translation in this action) runAction returns the generic 'This value conflicts with an existing record' message, leaving the Steward with no indication that the real fix is to clear the pending edits first.

**Evidence:** services/duplicates.ts:271-275 moves all edits by customerId with no state filter and no P2002 handling; the surrounding tx is the sorted-FOR-UPDATE merge (duplicates.ts:239-353). Index def at prisma/migrations/20260509150000_qa_remediation/migration.sql:12. No data corruption occurs (the tx is atomic and rolls back), but a legitimate Steward merge is blocked by an unexplained error.

**Scenario:** Two customers flagged as duplicates each have an in-flight SUBMITTED edit. Steward clicks Merge -> the edit-move updateMany trips the partial unique index -> merge rolls back -> Steward sees a generic conflict toast with no hint that the cause is the two pending edits.

## [32] P3 <concurrency> — UPDATE approve final transaction has no explicit timeout (default 5s) while the structurally-similar CREATE finalize uses 30s
**File:** `services/edits.ts:1084`

**Claim:** The FINAL-step UPDATE approve wraps claim + editApproval + applyEditChanges + audit + notify in `prisma.$transaction(async (tx) => {...})` with NO options object, so it runs under Prisma's default 5s interactive-transaction timeout. applyEditChanges fans out per branch (version read + versioned updateMany each) plus a full completeness recompute that reads every live branch and updates the customer and each branch, then notifyUsers — the same multi-statement fan-out that led the CREATE finalize path (edits.ts:874/941) to be bumped to `{ timeout: 30_000, maxWait: 10_000 }`. For a many-branch customer under Neon latency the UPDATE approve can exceed 5s and roll back. This is retryable and does not corrupt data (the atomic claim rolls back with it), but it is an asymmetry the CREATE fix did not carry over to UPDATE.

**Evidence:** services/edits.ts:1084 opens the tx with no options; contrast the CREATE finalize tx at edits.ts:906-941 which passes { timeout: 30_000, maxWait: 10_000 } with a comment 'finalize fans out ~7 statements per branch (up to 10 branches)'. applyEditChanges (edits.ts:580-690) does per-branch version read+update plus a completeness recompute over all branches (findUniqueOrThrow include branches, then update per branch).

**Scenario:** A Steward/Supervisor approves an UPDATE edit that touches several branches on a customer that itself has many branches; the completeness-recompute loop plus versioned updates exceed 5s on a cold/loaded Neon pool -> P2 rollback -> approve fails with a generic error and must be retried.

## [33] P3 <edge-null> — Stale workweek comment in SLA calendar contradicts the owner-confirmed Sun–Thu default (incompletely-updated workweek fix)
**File:** `lib/working-hours.ts:16`

**Claim:** The module header comment (line 16) still reads 'Defaults: Sun–Thu + Sat working (Friday off — OLD parity)', directly contradicting the actual default WORK_DAYS='0,1,2,3,4' (Sun–Thu, Saturday OFF) and the corrected inline comment on lines 23-24 ('Owner-confirmed workweek is Sun–Thu (5-day); Fri (5) AND Sat (6) are off'). The workweek fix updated the code default and the inline comment but left the header comment stale.

**Evidence:** Line 16: `* off — OLD parity), 08:00–17:00 Oman.` preceded by 'Sun–Thu + Sat working (Friday off'. Line 21-24: `const WORK_DAYS = new Set((process.env.WORK_DAYS ?? '0,1,2,3,4')...)` with comment 'Owner-confirmed workweek is Sun–Thu (5-day); Fri (5) AND Sat (6) are off.' The two comments disagree on whether Saturday is a working day.

**Scenario:** No runtime harm — the code default (0,1,2,3,4 = Sun–Thu) is correct. Risk is operational: an operator reading the header comment to set WORK_DAYS could re-add Saturday (6), which would mis-time every reviewer's working-hours SLA deadline. Low severity (documentation-only), included because it sits in SLA-critical code and is a leftover from the recent workweek fix.

## [34] P3 <fresh-eyes> — Completeness 'notes' dimension is dead — paymentTerms makes the guard always true
**File:** `lib/completeness.ts:47`

**Claim:** In scoreCustomerOnly, `if (c.notes || c.paymentTerms) s += 5;` awards its 5-point dimension unconditionally, because paymentTerms is a mandatory non-null Prisma enum (CASH|CREDIT) and is therefore always truthy. The `notes` field can never change the score; the intended 'has notes/terms' completeness signal is inert.

**Evidence:** completeness.ts:47 reads `if (c.notes || c.paymentTerms) s += 5;`. Customer.paymentTerms is a required enum on every Customer (schema + create-finalize.ts:180-194 always sets it), so the right operand is always truthy and short-circuits regardless of notes. The score feeds display rings (components/nmwc/CompletenessRing.tsx), the dashboard average (app/(app)/dashboard/page.tsx:84), and the completeness FILTER (lib/customer-filters.ts:192-196 minScore/maxScore) — so a Steward filtering for incomplete masters, or the dashboard avg, silently ignores whether notes were ever captured. No data-integrity, authz, approval, or Temix impact — cosmetic/metric only.

**Scenario:** Two otherwise-identical customers, one with detailed notes and one with none, receive the same completenessScore; a Steward filtering customers by maxScore to find records needing enrichment gets results that never account for the notes field.

## [35] P3 <fresh-eyes> — Stale working-hours header comment contradicts owner-confirmed Sun–Thu workweek
**File:** `lib/working-hours.ts:16`

**Claim:** The module header comment states the default workweek is 'Sun–Thu + Sat working (Friday off — OLD parity)', but the actual default implemented at lines 21-24 is WORK_DAYS = '0,1,2,3,4' (Sun–Thu; both Fri=5 AND Sat=6 off). The comment was not updated when the owner-confirmed Sun–Thu (5-day) decision landed, so it now describes a 6-day week the code no longer uses.

**Evidence:** working-hours.ts:16-17 header says `Defaults: Sun–Thu + Sat working (Friday off — OLD parity), 08:00–17:00 Oman.` while working-hours.ts:21-24 sets `const WORK_DAYS = new Set((process.env.WORK_DAYS ?? '0,1,2,3,4')...)` with an inline comment `Fri (5) AND Sat (6) are off.` The runtime default is correct; only the header is wrong.

**Scenario:** An operator tuning SLA/calendar config reads the header, believes Saturday is a working day by default, and mis-sets WORK_DAYS or reasons about SLA deadlines incorrectly — retiming every new submission's slaDueAt.

## [36] P3 <fresh-eyes> — NMWC code year derived from UTC runtime, not Oman (UTC+4) business time
**File:** `lib/create-finalize.ts:175`

**Claim:** allocateCustomerCode uses `finalizedAt.getFullYear()`, which on Vercel (UTC runtime) yields the UTC year, whereas the rest of the app deliberately shifts to Asia/Muscat (UTC+4, no DST) for business time (working-hours.ts:20/50-55). A finalize during 20:00–24:00 UTC on Dec 31 (= 00:00–04:00 Jan 1 in Oman) mints a previous-year NMWC-YYYY code for a customer whose Oman creation date is January 1.

**Evidence:** create-finalize.ts:175 `const nmwcCode = await allocateCustomerCode(tx, finalizedAt.getFullYear());` with finalizedAt = new Date() from approveEditCore (services/edits.ts:873). getFullYear() is local (UTC) time; there is no +240min shift like working-hours.ts:20 (`WORK_TZ_OFFSET_MIN ?? 240`). The per-year atomic counter (scope `CUSTOMER-<year>`) means no collision or corruption results — the Jan-1-Oman customer simply continues the prior year's sequence — so this is a cosmetic year-label mismatch, not a data-integrity bug.

**Scenario:** A customer approved at 2026-12-31 22:00 UTC (2027-01-01 02:00 Muscat) is assigned NMWC-2026-000NNN and consumes a 2026 sequence slot, even though its Oman business creation date is 2027-01-01.

## Completeness critic
COMPLETENESS-CRITIC VERDICT: After reading the auth stack, cron wiring, backup workflow, pagination, and upload path, almost every "candidate missed area" in the prompt turned out to be ALREADY covered — with ONE real exception the 18 passes missed: the Next.js Server Action body-size limit silently defeating the import workflow.

PRIMARY MISSED GAP (P2, verified from code) — Import upload breaks for any .xlsx > 1 MB. Next.js Server Actions cap the request body at 1 MB by default (next@15.5.18, confirmed in package.json / node_modules/next/package.json). next.config.ts (lines 40-50) sets NO experimental.serverActions.bodySizeLimit, and a repo-wide grep for "bodySizeLimit"/"serverActions" returns ZERO hits (checked next.config.ts, vercel.json, package.json, app/). The two importers are Server Actions, invoked directly from a client component: app/(app)/import/forms.tsx:28 does `await action(fd)` where action = uploadCustomerMasterAction / uploadAccountMasterAction (services/imports.ts:82 and its customer twin, both `SafeAction`, called with a FormData carrying the File). Because the File rides the Server-Action transport, Next.js rejects the whole request at the framework layer as soon as the encoded body exceeds 1 MB — BEFORE the app's own MAX_IMPORT_BYTES = 5 MB check (services/imports.ts:99 and :547) or parseWorkbook / MAX_TOTAL_ROWS = 50_000 (lib/excel.ts:12,27,75) ever run. The Steward sees an opaque framework error, surfaced verbatim through forms.tsx:44-48 (err.message), with none of the actionable "File too large / split the file" messaging the code was written to give. This directly undercuts the CORE go-live data-onboarding path: the code deliberately targets 5 MB / 50 k-row files (the comment at excel.ts:11 anticipates the ~3,300-customer master plus much larger ACCOUNT-master and Temix files), yet the framework silently caps at 1 MB. A realistic account-master or Temix export (tens of thousands of rows) will exceed 1 MB and fail to import. Fix: set experimental.serverActions.bodySizeLimit (e.g. '6mb', headroom over the 5 MB app cap) OR route the upload through a Route Handler like the R2 presign path already does. Workaround (split the file) exists, so P2 not P1 — but it can block the initial bulk migration depending on file size.

TWO SECONDARY residual gaps (lower priority, listed for completeness, NOT launch-blockers):
(a) P3 — lib/excel.ts:27 `wb.xlsx.load(u8)` fully materializes the entire workbook into memory before the MAX_TOTAL_ROWS guard (excel.ts:75) can fire. The row cap defends the downstream per-row DB loops (as its comment says), NOT parse-time RSS, so the decompression-bomb *memory* vector the comment at excel.ts:7-12 claims to close is not actually closed at load(). Now bounded by gap #1 (≤1 MB input) + Steward-only, so severity is low, but the mitigation is misdescribed.
(b) P3/ops — AuditLog has NO retention/archival anywhere. lib/audit.ts writeAudit fires on every login success AND fail (lib/auth.ts:112,297,309), logout (app/actions/auth.ts:87), and every edit/approval/escalation/import/route mutation. The sla-escalate cron GCs Notification rows older than 90 days (app/api/cron/sla-escalate/route.ts:280-290) and photo-gc prunes attachments — but nothing ever prunes or partitions AuditLog. At ~30 users / 3,300 customers the growth rate is modest, so this is a post-launch ops item, not go-live-critical.

Everything else in the prompt's candidate list was verified as adequately handled and is NOT a gap: Auth.js session/cookie/JWT freshness+revocation (lib/auth.ts:83-217, auth.config.ts:19-32), secret-entropy assert (lib/auth.ts:17-32), password force-change + reuse history (services/users.ts:425-478), backup/restore (.github/workflows/db-backup.yml incl. restore-drill), keep-warm + sla-escalate crons (GitHub Actions workflows, not vercel.json), pagination (PAGE_SIZE=50 on /customers and /audit), over-fetched client props (CustomerCard is a server component with no secret fields), and xlsx row-count DoS (MAX_TOTAL_ROWS). Secret rotation is already an owner-tracked open item in memory, so not "missed." No file edits, DB, or .env were touched; every citation was personally read.

## Regression critic
FINAL REGRESSION-CRITIC PASS (static only; every cite personally read). PER-FIX VERDICTS: [permissions.ts SR-USR-01] CORRECT+COMPLETE. Allowlist [SALESMAN,SUPERVISOR,VIEWER] at 223-227; canMutateUser 234-254 denies MANAGER on FM/GM/ACCOUNTANT/MANAGER/STEWARD; both role surfaces gate on it (users.ts:83,347; imports.ts F-02 266-291 + VALID_ROLES:70 omits approvers). Note: last-Manager guards (users.ts:204-214,356-365) are now unreachable dead code since canMutateUser blocks MANAGER-on-MANAGER and requireManager blocks STEWARD actor — admin tier mutable only out-of-band, as designed. [permissions.ts canApproveSpecificEdit/canActOnStep] CORRECT+COMPLETE (self-approval 138/180, prior-step SoD 181, fail-closed Manager overlap 143-145, REGION_OVERLAP 198-201, GLOBAL 206). [customer-filters customerListBranchScope SR-M2] CORRECT+COMPLETE, verified line-by-line against twin access.canSeeCustomer 67-104, default fail-closed 154. [customer-filters mergeStringIn SR-EXP-01] CORRECT+COMPLETE; empty {in:[]} stays empty 279; the empty-set branch is now defensive because all empty scopes route via forceEmpty (page 74-76, export 129-131) never an empty {in:[]}; traced Manager/Salesman/empty-team-Supervisor filter combos — all fail-closed to __none__. [page.tsx + customer-export shared scope] CORRECT+COMPLETE for the DATA boundary (identical helper inputs; forceEmpty->baseWhere.id=__none__; branch include mirrors where). [duplicates.ts merge PROD-DUP-01] CORRECT+COMPLETE: sorted FOR UPDATE 248-249, in-tx liveness recheck 251-264, loser atomic claim guarded on temixSyncState 297-306, winner re-queue in [SYNCED,UPLOADED]->PENDING_UPLOAD 315-318, resolveArchiveTemixState from FRESH in-tx read 292-296, 20s tx 352. Temix cross-check: loser DEACTIVATE + winner UPSERT-with-absorbed-branches = no Temix loss. [imports.ts promote branch-steal/dedup QA P-01/P-02/P-03 + F-17] CORRECT for the paths exercised: custcode-branchcode composition 929-940, in-group dup reject 959-983, in-tx owner guard 1141-1164, F-17 route/region-consistent UNASSIGNED pair 901-922, refresh presence-aware terms 1053-1071. [synthetic.ts E1 + constraint-smoke E3] CORRECT+COMPLETE: prod-endpoint guard exits 2 (synthetic 40-48), smoke asserts REQUIRED/MUST_BE_ABSENT and exits 3 (72-87), incl. asserting the dropped phone-unique index is ABSENT (28,73). [working-hours WORK_DAYS Sun-Thu] runtime constant CORRECT (0,1,2,3,4 line 22) but docstrings stale — see P3 #3. === FINDINGS === P2 #1 (data-integrity, imports.ts account import): services/imports.ts:389 sets ownedRoute:{disconnect:true} whenever ownedRouteId is null, and ownedRouteId is resolved ONLY when the SHEET role===SALESMAN (307-347); but role is applied only if wantsRoleChange (403, QA-011). So an EXISTING salesman re-imported with a mismatched role column (e.g. 'SUPERVISOR') and change_role BLANK keeps role=SALESMAN yet has ownedRoute DISCONNECTED. Result: a salesman with no route -> canSeeCustomer(SALESMAN) returns false (access.ts:81), /today empty, total silent customer-visibility loss, NO audit row (the 334-344 audit only fires on SALESMAN rows displacing others). This defeats QA-011's own intent: role is protected from silent change but its route side-effect is not. Trigger = steward edits a role in the master sheet but forgets change_role=yes (plausible during restructuring). Fix: gate the ownedRoute disconnect on the EFFECTIVE (post-QA-011) role, not the sheet role — when not changing role, leave ownedRoute untouched. P2 #2 (data-completeness on real master load, imports.ts customer master): cross-cust_code phone duplicates are quarantined both in-file (672-674) and vs master (675-677). This CONTRADICTS two deliberate session decisions: (a) migration 20260510160000_p1_drop_phone_unique dropped the phone-unique index (asserted absent in constraint-smoke:25-28,73), and (b) duplicates.ts:42-54 dropped phone-only detection because 'one owner often runs many shops with the same primaryPhone — phone duplicates are LEGITIMATE'. On the real ~3,300 master, legitimate same-owner multi-shop customers (DIFFERENT nmwcCodes, shared phone) will be quarantined. Promote reads ONLY CLEAN rows (807-809) and the batch page (import/[batchId]/page.tsx:42-45) offers no un-quarantine/edit action, so those customers are WITHHELD from the master until the steward hand-fixes and re-uploads. Distinct from the fixed F-UAT-7 (that was SAME-cust_code self-collision; synthetic phones are unique so the medium-master residual was indeed the self-collision, now fixed). CR-side quarantine is correct (CR dup is a true signal); only the PHONE-side conflicts. Fix: drop the cross-custcode phone quarantine (or make it a non-blocking warning), matching the phone-dup-is-legitimate policy. P3 #3 (working-hours.ts stale docs): header 14-16 says default 'Sun-Thu + Sat working (Friday off - OLD parity)' and the slaDeadline example 90-93 says a Thu 16:30 +60m budget is 'due 08:30 Saturday' — both describe the OLD 6-day week. Actual default is 0,1,2,3,4 (Sun-Thu, Sat now OFF; comment 23-24 is right), so that example is now due 08:30 SUNDAY. Runtime is correct; only comments are stale after the workweek change (commits 4044182/f1d0505) and could mislead ops setting WORK_DAYS. P3 #4 (customers/page.tsx export/dropdown drift for approver roles): page.tsx:125 sets canExport = me.role !== SALESMAN, but the export server action (customer-export.ts:42-49 requireExportRole) and permissions.canExport (43-50) allow only MANAGER/STEWARD/VIEWER/SUPERVISOR. So ACCOUNTANT/FINANCE_MANAGER/GM (who can browse /customers) see an Export button whose action throws 'Your role cannot export.' Also the filter-dropdown scope branches (page.tsx:196-229) handle only SUPERVISOR/MANAGER, so an ACCOUNTANT's region+salesman dropdowns list ALL regions/salesmen. NO DATA LEAK — the where-clause fail-closes via customerListBranchScope+mergeStringIn (out-of-scope picks intersect to __none__) — purely cosmetic. Fix: use permissions.canExport for the button and add ACCOUNTANT to the dropdown scope branches.</notes>
<parameter name="gaps">["Could not exercise runtime: findings are static. #1 (ownedRoute disconnect) and #2 (phone quarantine on real master) should be confirmed with an integration test — #1 with an existing SALESMAN row carrying a non-SALESMAN role + blank change_role; #2 with two different cust_codes sharing one normalized phone.", "Did not audit lib/approval-chains.ts SLA-budget-freeze internals beyond confirming it consumes working-hours slaDeadline/STAGE_SLA_MINUTES; the f1d0505 fixture change was assumed correct given the Sun-Thu constant is right.", "Refresh-row interaction in promote: a Temix REFRESH group (temix_code present) still runs the pre-tx duplicate-branchCode reject (959-983) and region/route resolution even though branches are never touched (1131). If a refresh sheet ever carries branch_code columns with an intra-group dup, the whole refresh (incl. credit fields) would be rejected. Could not confirm real refresh sheets carry branch codes, so left unreported.", "Did not verify whether a Manager's managedRegions can be reassigned via account import (imports.ts:449-456 uses set) is an intended Steward power vs a scope-change concern; treated as intended per out-of-band provisioning note."]

