-- Phase 1 (part 2/2): CREATE-request spine (typed drafts), credit fields, Temix
-- sync queue, multi-step approval fields, SLA, notifications.
--
-- Structural DDL below the header was generated by `prisma migrate diff`
-- (drift-free vs schema.prisma). Hand-written invariants (backfill, the
-- branch-side open-edit partial unique, and the B-19/B-20 CHECK/trigger rules
-- mirrored from the live Branch table) are appended at the end.

-- AlterTable
ALTER TABLE "Customer" ADD COLUMN     "creditLimit" DECIMAL(14,3),
ADD COLUMN     "lastTemixUploadAt" TIMESTAMP(3),
ADD COLUMN     "lastTemixUploadBatchId" TEXT,
ADD COLUMN     "paymentTermDays" INTEGER,
ADD COLUMN     "temixCode" TEXT,
ADD COLUMN     "temixSyncPendingSince" TIMESTAMP(3),
ADD COLUMN     "temixSyncState" "TemixSyncState" NOT NULL DEFAULT 'SYNCED';

-- AlterTable
ALTER TABLE "CustomerEdit" ADD COLUMN     "approvalChain" JSONB,
ADD COLUMN     "currentStepIndex" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "cycle" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "escalationLevel" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastEscalatedAt" TIMESTAMP(3),
ADD COLUMN     "paymentTermsAtSubmit" "PaymentTerms",
ADD COLUMN     "pendingRole" "Role",
ADD COLUMN     "process" "EditProcess" NOT NULL DEFAULT 'UPDATE',
ADD COLUMN     "requestedCreditLimit" DECIMAL(14,3),
ADD COLUMN     "requestedPaymentTermDays" INTEGER,
ADD COLUMN     "slaBreachedAt" TIMESTAMP(3),
ADD COLUMN     "slaDueAt" TIMESTAMP(3),
ADD COLUMN     "stageEnteredAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Attachment" ADD COLUMN     "editId" TEXT;

-- CreateTable
CREATE TABLE "EditCustomerDraft" (
    "id" TEXT NOT NULL,
    "editId" TEXT NOT NULL,
    "legalName" TEXT NOT NULL,
    "paymentTerms" "PaymentTerms" NOT NULL,
    "crNumber" TEXT,
    "crNumberNorm" TEXT,
    "channelId" TEXT,
    "subChannelId" TEXT,
    "primaryPhone" TEXT,
    "primaryPhoneNorm" TEXT,
    "altPhone" TEXT,
    "contactPerson" TEXT,
    "contactRole" TEXT,
    "notes" TEXT,
    "crPhotoAttachmentId" TEXT,

    CONSTRAINT "EditCustomerDraft_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EditBranchDraft" (
    "id" TEXT NOT NULL,
    "editId" TEXT NOT NULL,
    "branchName" TEXT NOT NULL,
    "regionId" TEXT NOT NULL,
    "routeId" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "areaDescription" TEXT,
    "gpsLat" DOUBLE PRECISION,
    "gpsLng" DOUBLE PRECISION,
    "gpsAccuracy" DOUBLE PRECISION,
    "gpsCapturedAt" TIMESTAMP(3),
    "dayOfVisit" "DayOfWeek",
    "openingHours" TEXT,
    "deliveryWindow" TEXT,
    "coolersCount" INTEGER NOT NULL DEFAULT 0,
    "standsCount" INTEGER NOT NULL DEFAULT 0,
    "emptyBottlesCount" INTEGER NOT NULL DEFAULT 0,
    "shopPhotoAttachmentId" TEXT,
    "signboardPhotoAttachmentId" TEXT,
    "extraPhotoAttachmentIds" JSONB,

    CONSTRAINT "EditBranchDraft_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EditApproval" (
    "id" TEXT NOT NULL,
    "editId" TEXT NOT NULL,
    "cycle" INTEGER NOT NULL,
    "stepIndex" INTEGER NOT NULL,
    "role" "Role" NOT NULL,
    "decision" TEXT NOT NULL,
    "actorId" TEXT NOT NULL,
    "reason" TEXT,
    "at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EditApproval_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Notification" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "kind" "NotificationKind" NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "editId" TEXT,
    "customerId" TEXT,
    "readAt" TIMESTAMP(3),
    "emailedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TemixSyncBatch" (
    "id" TEXT NOT NULL,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "rowCount" INTEGER NOT NULL DEFAULT 0,
    "customerIds" JSONB NOT NULL,
    "status" "ExportJobStatus" NOT NULL DEFAULT 'PENDING',
    "r2Key" TEXT,
    "markedLoadedAt" TIMESTAMP(3),

    CONSTRAINT "TemixSyncBatch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CodeSequence" (
    "scope" TEXT NOT NULL,
    "next" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "CodeSequence_pkey" PRIMARY KEY ("scope")
);

-- CreateIndex
CREATE UNIQUE INDEX "EditCustomerDraft_editId_key" ON "EditCustomerDraft"("editId");

-- CreateIndex
CREATE UNIQUE INDEX "EditCustomerDraft_crPhotoAttachmentId_key" ON "EditCustomerDraft"("crPhotoAttachmentId");

-- CreateIndex
CREATE INDEX "EditCustomerDraft_crNumberNorm_idx" ON "EditCustomerDraft"("crNumberNorm");

-- CreateIndex
CREATE INDEX "EditCustomerDraft_primaryPhoneNorm_idx" ON "EditCustomerDraft"("primaryPhoneNorm");

-- CreateIndex
CREATE INDEX "EditBranchDraft_editId_idx" ON "EditBranchDraft"("editId");

-- CreateIndex
CREATE INDEX "EditApproval_editId_at_idx" ON "EditApproval"("editId", "at" DESC);

-- CreateIndex
CREATE INDEX "EditApproval_actorId_idx" ON "EditApproval"("actorId");

-- CreateIndex
CREATE INDEX "Notification_userId_readAt_idx" ON "Notification"("userId", "readAt");

-- CreateIndex
CREATE INDEX "Notification_emailedAt_createdAt_idx" ON "Notification"("emailedAt", "createdAt");

-- CreateIndex
CREATE INDEX "Notification_editId_idx" ON "Notification"("editId");

-- CreateIndex
CREATE INDEX "Customer_temixCode_idx" ON "Customer"("temixCode");

-- CreateIndex
CREATE INDEX "Customer_temixSyncState_idx" ON "Customer"("temixSyncState");

-- CreateIndex
CREATE INDEX "CustomerEdit_pendingRole_state_idx" ON "CustomerEdit"("pendingRole", "state");

-- CreateIndex
CREATE INDEX "CustomerEdit_state_slaDueAt_idx" ON "CustomerEdit"("state", "slaDueAt");

-- CreateIndex
CREATE INDEX "Attachment_editId_idx" ON "Attachment"("editId");

-- AddForeignKey
ALTER TABLE "Attachment" ADD CONSTRAINT "Attachment_editId_fkey" FOREIGN KEY ("editId") REFERENCES "CustomerEdit"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EditCustomerDraft" ADD CONSTRAINT "EditCustomerDraft_editId_fkey" FOREIGN KEY ("editId") REFERENCES "CustomerEdit"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EditCustomerDraft" ADD CONSTRAINT "EditCustomerDraft_channelId_fkey" FOREIGN KEY ("channelId") REFERENCES "Channel"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EditCustomerDraft" ADD CONSTRAINT "EditCustomerDraft_subChannelId_fkey" FOREIGN KEY ("subChannelId") REFERENCES "SubChannel"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EditBranchDraft" ADD CONSTRAINT "EditBranchDraft_editId_fkey" FOREIGN KEY ("editId") REFERENCES "CustomerEdit"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EditBranchDraft" ADD CONSTRAINT "EditBranchDraft_regionId_fkey" FOREIGN KEY ("regionId") REFERENCES "Region"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EditBranchDraft" ADD CONSTRAINT "EditBranchDraft_routeId_fkey" FOREIGN KEY ("routeId") REFERENCES "Route"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EditApproval" ADD CONSTRAINT "EditApproval_editId_fkey" FOREIGN KEY ("editId") REFERENCES "CustomerEdit"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EditApproval" ADD CONSTRAINT "EditApproval_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_editId_fkey" FOREIGN KEY ("editId") REFERENCES "CustomerEdit"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TemixSyncBatch" ADD CONSTRAINT "TemixSyncBatch_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ── Backfill: every pre-Phase-1 edit is a 1-step UPDATE. `process` already
-- defaults to UPDATE; set the frozen chain + denormalized pendingRole/
-- stageEnteredAt for rows still pending so the new queue/SLA queries see them. ──
UPDATE "CustomerEdit"
SET "approvalChain"  = '[{"role":"SUPERVISOR","scope":"SUPERVISOR_OF_SUBMITTER","slaHours":8}]'::jsonb,
    "pendingRole"    = CASE WHEN "state" = 'SUBMITTED' THEN 'SUPERVISOR'::"Role" ELSE NULL END,
    "stageEnteredAt" = CASE WHEN "state" = 'SUBMITTED' THEN "submittedAt" ELSE NULL END
WHERE "approvalChain" IS NULL;

-- ── One open (SUBMITTED) edit per BRANCH — the branch-side twin of the existing
-- CustomerEdit_open_per_customer partial unique (closes new-data.md §4.4 gap). ──
CREATE UNIQUE INDEX IF NOT EXISTS "CustomerEdit_open_per_branch"
  ON "CustomerEdit" ("branchId")
  WHERE "state" = 'SUBMITTED' AND "branchId" IS NOT NULL;

-- ── EditBranchDraft: mirror the live Branch DB invariants (B-20 GPS range +
-- address minlength, B-19 region==route consistency) so a net-new branch drafted
-- via a CREATE request gets the same guarantees. GPS bounds are global here (the
-- Oman envelope stays app-level Zod, exactly like the live Branch table). ──
DO $$ BEGIN
  ALTER TABLE "EditBranchDraft" ADD CONSTRAINT "EditBranchDraft_gpsLat_range"
    CHECK ("gpsLat" IS NULL OR ("gpsLat" >= -90 AND "gpsLat" <= 90));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "EditBranchDraft" ADD CONSTRAINT "EditBranchDraft_gpsLng_range"
    CHECK ("gpsLng" IS NULL OR ("gpsLng" >= -180 AND "gpsLng" <= 180));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "EditBranchDraft" ADD CONSTRAINT "EditBranchDraft_address_minlength"
    CHECK (length(btrim("address")) >= 3);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DROP TRIGGER IF EXISTS editbranchdraft_region_consistency_check ON "EditBranchDraft";
CREATE TRIGGER editbranchdraft_region_consistency_check
  BEFORE INSERT OR UPDATE OF "regionId", "routeId" ON "EditBranchDraft"
  FOR EACH ROW EXECUTE FUNCTION enforce_branch_region_consistency();

-- ── Credit-figure sanity CHECKs on Customer + CustomerEdit. ──
DO $$ BEGIN
  ALTER TABLE "Customer" ADD CONSTRAINT "Customer_creditLimit_nonneg"
    CHECK ("creditLimit" IS NULL OR "creditLimit" >= 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "Customer" ADD CONSTRAINT "Customer_paymentTermDays_range"
    CHECK ("paymentTermDays" IS NULL OR ("paymentTermDays" BETWEEN 0 AND 365));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "CustomerEdit" ADD CONSTRAINT "CustomerEdit_reqCreditLimit_nonneg"
    CHECK ("requestedCreditLimit" IS NULL OR "requestedCreditLimit" >= 0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "CustomerEdit" ADD CONSTRAINT "CustomerEdit_reqPaymentTermDays_range"
    CHECK ("requestedPaymentTermDays" IS NULL OR ("requestedPaymentTermDays" BETWEEN 0 AND 365));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
